spring.application.name=CaloriesCalculator
#utilizando o a dependencia do banco h2, conseguimos deixar salvo no disco rigido, trocar mais tarde
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#para configurar tempo de sessão dos usuarios
server.servlet.session.timeout=1m
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
