INSERT INTO PRODUTO_ALIMENTICIO (ID, CARBOIDRATOS, DESCRICAO, GORDURA_GERAIS, KCAL, PESO, PROTEINAS, TIPO, TITULO) VALUES
(1, 25.8, 'Alimento da categoria Cereais e derivados, nome Arroz integral cozido', 0, 124, 100, 2.6, 'Cereais e derivados', 'Arroz integral cozido'),
(2, 77.5, 'Alimento da categoria Cereais e derivados, nome Arroz integral cru', 0, 360, 100, 7.3, 'Cereais e derivados', 'Arroz integral cru'),
(3, 28.1, 'Alimento da categoria Cereais e derivados, nome Arroz tipo 1 cozido', 0, 128, 100, 2.5, 'Cereais e derivados', 'Arroz tipo 1 cozido'),
(4, 78.8, 'Alimento da categoria Cereais e derivados, nome Arroz tipo 1 cru', 0, 358, 100, 7.2, 'Cereais e derivados', 'Arroz tipo 1 cru'),
(5, 28.2, 'Alimento da categoria Cereais e derivados, nome Arroz tipo 2 cozido', 0, 130, 100, 2.6, 'Cereais e derivados', 'Arroz tipo 2 cozido'),
(6, 78.9, 'Alimento da categoria Cereais e derivados, nome Arroz tipo 2 cru', 0, 358, 100, 7.2, 'Cereais e derivados', 'Arroz tipo 2 cru'),
(7, 66.6, 'Alimento da categoria Cereais e derivados, nome Aveia flocos crua', 0, 394, 100, 13.9, 'Cereais e derivados', 'Aveia flocos crua'),
(8, 75.2, 'Alimento da categoria Cereais e derivados, nome Biscoito doce maisena', 0, 443, 100, 8.1, 'Cereais e derivados', 'Biscoito doce maisena'),
(9, 70.5, 'Alimento da categoria Cereais e derivados, nome Biscoito doce recheado com chocolate', 0, 472, 100, 6.4, 'Cereais e derivados', 'Biscoito doce recheado com chocolate'),
(10, 71, 'Alimento da categoria Cereais e derivados, nome Biscoito doce recheado com morango', 0, 471, 100, 5.7, 'Cereais e derivados', 'Biscoito doce recheado com morango'),
(11, 67.5, 'Alimento da categoria Cereais e derivados, nome Biscoito doce wafer recheado de chocolate', 0, 502, 100, 5.6, 'Cereais e derivados', 'Biscoito doce wafer recheado de chocolate'),
(12, 67.4, 'Alimento da categoria Cereais e derivados, nome Biscoito doce wafer recheado de morango', 0, 513, 100, 4.5, 'Cereais e derivados', 'Biscoito doce wafer recheado de morango'),
(13, 68.7, 'Alimento da categoria Cereais e derivados, nome Biscoito salgado cream cracker', 0, 432, 100, 10.1, 'Cereais e derivados', 'Biscoito salgado cream cracker'),
(14, 84.7, 'Alimento da categoria Cereais e derivados, nome Bolo mistura para', 0, 419, 100, 6.2, 'Cereais e derivados', 'Bolo mistura para'),
(15, 47.9, 'Alimento da categoria Cereais e derivados, nome Bolo pronto aipim', 0, 324, 100, 4.4, 'Cereais e derivados', 'Bolo pronto aipim'),
(16, 54.7, 'Alimento da categoria Cereais e derivados, nome Bolo pronto chocolate', 0, 410, 100, 6.2, 'Cereais e derivados', 'Bolo pronto chocolate'),
(17, 52.3, 'Alimento da categoria Cereais e derivados, nome Bolo pronto coco', 0, 333, 100, 5.7, 'Cereais e derivados', 'Bolo pronto coco'),
(18, 45.1, 'Alimento da categoria Cereais e derivados, nome Bolo pronto milho', 0, 311, 100, 4.8, 'Cereais e derivados', 'Bolo pronto milho'),
(19, 78.1, 'Alimento da categoria Cereais e derivados, nome Canjica branca crua', 0, 358, 100, 7.2, 'Cereais e derivados', 'Canjica branca crua'),
(20, 23.6, 'Alimento da categoria Cereais e derivados, nome Canjica com leite integral', 0, 112, 100, 2.4, 'Cereais e derivados', 'Canjica com leite integral'),
(21, 80.8, 'Alimento da categoria Cereais e derivados, nome Cereais milho flocos com sal', 0, 370, 100, 7.3, 'Cereais e derivados', 'Cereais milho flocos com sal'),
(22, 80.4, 'Alimento da categoria Cereais e derivados, nome Cereais milho flocos sem sal', 0, 363, 100, 6.9, 'Cereais e derivados', 'Cereais milho flocos sem sal'),
(23, 87.3, 'Alimento da categoria Cereais e derivados, nome Cereais mingau milho infantil', 0, 394, 100, 6.4, 'Cereais e derivados', 'Cereais mingau milho infantil'),
(24, 81.6, 'Alimento da categoria Cereais e derivados, nome Cereais mistura para vitamina trigo cevada e aveia', 0, 381, 100, 8.9, 'Cereais e derivados', 'Cereais mistura para vitamina trigo cevada e aveia'),
(25, 83.8, 'Alimento da categoria Cereais e derivados, nome Cereal matinal milho', 0, 365, 100, 7.2, 'Cereais e derivados', 'Cereal matinal milho'),
(26, 88.8, 'Alimento da categoria Cereais e derivados, nome Cereal matinal milho açúcar', 0, 377, 100, 4.7, 'Cereais e derivados', 'Cereal matinal milho açúcar'),
(27, 83.9, 'Alimento da categoria Cereais e derivados, nome Creme de arroz pó', 0, 386, 100, 7, 'Cereais e derivados', 'Creme de arroz pó'),
(28, 86.1, 'Alimento da categoria Cereais e derivados, nome Creme de milho pó', 0, 333, 100, 4.8, 'Cereais e derivados', 'Creme de milho pó'),
(29, 13.9, 'Alimento da categoria Cereais e derivados, nome Curau milho verde', 0, 78, 100, 2.4, 'Cereais e derivados', 'Curau milho verde'),
(30, 79.8, 'Alimento da categoria Cereais e derivados, nome Curau milho verde mistura para', 0, 402, 100, 2.2, 'Cereais e derivados', 'Curau milho verde mistura para'),
(31, 85.5, 'Alimento da categoria Cereais e derivados, nome Farinha de arroz enriquecida', 0, 363, 100, 1.3, 'Cereais e derivados', 'Farinha de arroz enriquecida'),
(32, 73.3, 'Alimento da categoria Cereais e derivados, nome Farinha de centeio integral', 0, 336, 100, 12.5, 'Cereais e derivados', 'Farinha de centeio integral'),
(33, 79.1, 'Alimento da categoria Cereais e derivados, nome Farinha de milho amarela', 0, 351, 100, 7.2, 'Cereais e derivados', 'Farinha de milho amarela'),
(34, 75.8, 'Alimento da categoria Cereais e derivados, nome Farinha de rosca', 0, 371, 100, 11.4, 'Cereais e derivados', 'Farinha de rosca'),
(35, 75.1, 'Alimento da categoria Cereais e derivados, nome Farinha de trigo', 0, 360, 100, 9.8, 'Cereais e derivados', 'Farinha de trigo'),
(36, 77.8, 'Alimento da categoria Cereais e derivados, nome Farinha láctea de cereais', 0, 415, 100, 11.9, 'Cereais e derivados', 'Farinha láctea de cereais'),
(37, 32.5, 'Alimento da categoria Cereais e derivados, nome Lasanha massa fresca cozida', 0, 164, 100, 5.8, 'Cereais e derivados', 'Lasanha massa fresca cozida'),
(38, 45.1, 'Alimento da categoria Cereais e derivados, nome Lasanha massa fresca crua', 0, 220, 100, 7, 'Cereais e derivados', 'Lasanha massa fresca crua'),
(39, 62.4, 'Alimento da categoria Cereais e derivados, nome Macarrão instantâneo', 0, 436, 100, 8.8, 'Cereais e derivados', 'Macarrão instantâneo'),
(40, 77.9, 'Alimento da categoria Cereais e derivados, nome Macarrão trigo cru', 0, 371, 100, 10, 'Cereais e derivados', 'Macarrão trigo cru'),
(41, 76.6, 'Alimento da categoria Cereais e derivados, nome Macarrão trigo cru com ovos', 0, 371, 100, 10.3, 'Cereais e derivados', 'Macarrão trigo cru com ovos'),
(42, 87.1, 'Alimento da categoria Cereais e derivados, nome Milho amido cru', 0, 361, 100, 0.6, 'Cereais e derivados', 'Milho amido cru'),
(43, 78.9, 'Alimento da categoria Cereais e derivados, nome Milho fubá cru', 0, 353, 100, 7.2, 'Cereais e derivados', 'Milho fubá cru'),
(44, 28.6, 'Alimento da categoria Cereais e derivados, nome Milho verde cru', 0, 138, 100, 6.6, 'Cereais e derivados', 'Milho verde cru'),
(45, 17.1, 'Alimento da categoria Cereais e derivados, nome Milho verde enlatado drenado', 0, 98, 100, 3.2, 'Cereais e derivados', 'Milho verde enlatado drenado'),
(46, 89.3, 'Alimento da categoria Cereais e derivados, nome Mingau tradicional pó', 0, 373, 100, 0.6, 'Cereais e derivados', 'Mingau tradicional pó'),
(47, 30.7, 'Alimento da categoria Cereais e derivados, nome Pamonha barra para cozimento pré-cozida', 0, 171, 100, 2.6, 'Cereais e derivados', 'Pamonha barra para cozimento pré-cozida'),
(48, 59.6, 'Alimento da categoria Cereais e derivados, nome Pão aveia forma', 0, 343, 100, 12.4, 'Cereais e derivados', 'Pão aveia forma'),
(49, 56.5, 'Alimento da categoria Cereais e derivados, nome Pão de soja', 0, 309, 100, 11.3, 'Cereais e derivados', 'Pão de soja'),
(50, 44.1, 'Alimento da categoria Cereais e derivados, nome Pão glúten forma', 0, 253, 100, 12, 'Cereais e derivados', 'Pão glúten forma'),
(51, 56.4, 'Alimento da categoria Cereais e derivados, nome Pão milho forma', 0, 292, 100, 8.3, 'Cereais e derivados', 'Pão milho forma'),
(52, 49.9, 'Alimento da categoria Cereais e derivados, nome Pão trigo forma integral', 0, 253, 100, 9.4, 'Cereais e derivados', 'Pão trigo forma integral'),
(53, 58.6, 'Alimento da categoria Cereais e derivados, nome Pão trigo francês', 0, 300, 100, 8, 'Cereais e derivados', 'Pão trigo francês'),
(54, 61.5, 'Alimento da categoria Cereais e derivados, nome Pão trigo sovado', 0, 311, 100, 8.4, 'Cereais e derivados', 'Pão trigo sovado'),
(55, 42, 'Alimento da categoria Cereais e derivados, nome Pastel de carne cru', 0, 289, 100, 10.7, 'Cereais e derivados', 'Pastel de carne cru'),
(56, 43.8, 'Alimento da categoria Cereais e derivados, nome Pastel de carne frito', 0, 388, 100, 10.1, 'Cereais e derivados', 'Pastel de carne frito'),
(57, 45.9, 'Alimento da categoria Cereais e derivados, nome Pastel de queijo cru', 0, 308, 100, 9.9, 'Cereais e derivados', 'Pastel de queijo cru'),
(58, 48.1, 'Alimento da categoria Cereais e derivados, nome Pastel de queijo frito', 0, 422, 100, 8.7, 'Cereais e derivados', 'Pastel de queijo frito'),
(59, 57.4, 'Alimento da categoria Cereais e derivados, nome Pastel massa crua', 0, 310, 100, 6.9, 'Cereais e derivados', 'Pastel massa crua'),
(60, 49.3, 'Alimento da categoria Cereais e derivados, nome Pastel massa frita', 0, 570, 100, 6, 'Cereais e derivados', 'Pastel massa frita'),
(61, 70.3, 'Alimento da categoria Cereais e derivados, nome Pipoca com óleo de soja sem sal', 0, 448, 100, 9.9, 'Cereais e derivados', 'Pipoca com óleo de soja sem sal'),
(62, 23.3, 'Alimento da categoria Cereais e derivados, nome Polenta pré-cozida', 0, 103, 100, 2.3, 'Cereais e derivados', 'Polenta pré-cozida'),
(63, 74.6, 'Alimento da categoria Cereais e derivados, nome Torrada pão francês', 0, 377, 100, 10.5, 'Cereais e derivados', 'Torrada pão francês'),
(64, 10.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora cabotian cozida', 0, 48, 100, 1.4, 'Verduras, hortaliças e derivados', 'Abóbora cabotian cozida'),
(65, 8.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora cabotian crua', 0, 39, 100, 1.7, 'Verduras, hortaliças e derivados', 'Abóbora cabotian crua'),
(66, 3.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora menina brasileira crua', 0, 14, 100, 0.6, 'Verduras, hortaliças e derivados', 'Abóbora menina brasileira crua'),
(67, 2.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora moranga crua', 0, 12, 100, 1, 'Verduras, hortaliças e derivados', 'Abóbora moranga crua'),
(68, 6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora moranga refogada', 0, 29, 100, 0.4, 'Verduras, hortaliças e derivados', 'Abóbora moranga refogada'),
(69, 6.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abóbora pescoço crua', 0, 24, 100, 0.7, 'Verduras, hortaliças e derivados', 'Abóbora pescoço crua'),
(70, 3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abobrinha italiana cozida', 0, 15, 100, 1.1, 'Verduras, hortaliças e derivados', 'Abobrinha italiana cozida'),
(71, 4.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abobrinha italiana crua', 0, 19, 100, 1.1, 'Verduras, hortaliças e derivados', 'Abobrinha italiana crua'),
(72, 4.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abobrinha italiana refogada', 0, 24, 100, 1.1, 'Verduras, hortaliças e derivados', 'Abobrinha italiana refogada'),
(73, 7.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Abobrinha paulista crua', 0, 31, 100, 0.6, 'Verduras, hortaliças e derivados', 'Abobrinha paulista crua'),
(74, 4.6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Acelga crua', 0, 21, 100, 1.4, 'Verduras, hortaliças e derivados', 'Acelga crua'),
(75, 2.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Agrião cru', 0, 17, 100, 2.7, 'Verduras, hortaliças e derivados', 'Agrião cru'),
(76, 4.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Aipo cru', 0, 19, 100, 0.8, 'Verduras, hortaliças e derivados', 'Aipo cru'),
(77, 1.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alface americana crua', 0, 9, 100, 0.6, 'Verduras, hortaliças e derivados', 'Alface americana crua'),
(78, 1.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alface crespa crua', 0, 11, 100, 1.3, 'Verduras, hortaliças e derivados', 'Alface crespa crua'),
(79, 2.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alface lisa crua', 0, 14, 100, 1.7, 'Verduras, hortaliças e derivados', 'Alface lisa crua'),
(80, 2.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alface roxa crua', 0, 13, 100, 0.9, 'Verduras, hortaliças e derivados', 'Alface roxa crua'),
(81, 5.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alfavaca crua', 0, 29, 100, 2.7, 'Verduras, hortaliças e derivados', 'Alfavaca crua'),
(82, 23.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alho cru', 0, 113, 100, 7, 'Verduras, hortaliças e derivados', 'Alho cru'),
(83, 6.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Alho-poró cru', 0, 32, 100, 1.4, 'Verduras, hortaliças e derivados', 'Alho-poró cru'),
(84, 3.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Almeirão cru', 0, 18, 100, 1.8, 'Verduras, hortaliças e derivados', 'Almeirão cru'),
(85, 5.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Almeirão refogado', 0, 65, 100, 1.7, 'Verduras, hortaliças e derivados', 'Almeirão refogado'),
(86, 18.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata baroa cozida', 0, 80, 100, 0.9, 'Verduras, hortaliças e derivados', 'Batata baroa cozida'),
(87, 24, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata baroa crua', 0, 101, 100, 1, 'Verduras, hortaliças e derivados', 'Batata baroa crua'),
(88, 18.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata doce cozida', 0, 77, 100, 0.6, 'Verduras, hortaliças e derivados', 'Batata doce cozida'),
(89, 28.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata doce crua', 0, 118, 100, 1.3, 'Verduras, hortaliças e derivados', 'Batata doce crua'),
(90, 51.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata frita tipo chips industrializada', 0, 543, 100, 5.6, 'Verduras, hortaliças e derivados', 'Batata frita tipo chips industrializada'),
(91, 11.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata inglesa cozida', 0, 52, 100, 1.2, 'Verduras, hortaliças e derivados', 'Batata inglesa cozida'),
(92, 14.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata inglesa crua', 0, 64, 100, 1.8, 'Verduras, hortaliças e derivados', 'Batata inglesa crua'),
(93, 35.6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata inglesa frita', 0, 267, 100, 5, 'Verduras, hortaliças e derivados', 'Batata inglesa frita'),
(94, 14.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Batata inglesa sauté', 0, 68, 100, 1.3, 'Verduras, hortaliças e derivados', 'Batata inglesa sauté'),
(95, 4.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Berinjela cozida', 0, 19, 100, 0.7, 'Verduras, hortaliças e derivados', 'Berinjela cozida'),
(96, 4.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Berinjela crua', 0, 20, 100, 1.2, 'Verduras, hortaliças e derivados', 'Berinjela crua'),
(97, 7.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Beterraba cozida', 0, 32, 100, 1.3, 'Verduras, hortaliças e derivados', 'Beterraba cozida'),
(98, 11.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Beterraba crua', 0, 49, 100, 1.9, 'Verduras, hortaliças e derivados', 'Beterraba crua'),
(99, 80.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Biscoito polvilho doce', 0, 438, 100, 1.3, 'Verduras, hortaliças e derivados', 'Biscoito polvilho doce'),
(100, 4.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Brócolis cozido', 0, 25, 100, 2.1, 'Verduras, hortaliças e derivados', 'Brócolis cozido'),
(101, 4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Brócolis cru', 0, 25, 100, 3.6, 'Verduras, hortaliças e derivados', 'Brócolis cru'),
(102, 18.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cará cozido', 0, 78, 100, 1.5, 'Verduras, hortaliças e derivados', 'Cará cozido'),
(103, 23, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cará cru', 0, 96, 100, 2.3, 'Verduras, hortaliças e derivados', 'Cará cru'),
(104, 6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Caruru cru', 0, 34, 100, 3.2, 'Verduras, hortaliças e derivados', 'Caruru cru'),
(105, 4.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Catalonha crua', 0, 24, 100, 1.9, 'Verduras, hortaliças e derivados', 'Catalonha crua'),
(106, 4.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Catalonha refogada', 0, 63, 100, 2, 'Verduras, hortaliças e derivados', 'Catalonha refogada'),
(107, 8.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cebola crua', 0, 39, 100, 1.7, 'Verduras, hortaliças e derivados', 'Cebola crua'),
(108, 3.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cebolinha crua', 0, 20, 100, 1.9, 'Verduras, hortaliças e derivados', 'Cebolinha crua'),
(109, 6.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cenoura cozida', 0, 30, 100, 0.8, 'Verduras, hortaliças e derivados', 'Cenoura cozida'),
(110, 7.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Cenoura crua', 0, 34, 100, 1.3, 'Verduras, hortaliças e derivados', 'Cenoura crua'),
(111, 2.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Chicória crua', 0, 14, 100, 1.1, 'Verduras, hortaliças e derivados', 'Chicória crua'),
(112, 4.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Chuchu cozido', 0, 19, 100, 0.4, 'Verduras, hortaliças e derivados', 'Chuchu cozido'),
(113, 4.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Chuchu cru', 0, 17, 100, 0.7, 'Verduras, hortaliças e derivados', 'Chuchu cru'),
(114, 48, 'Alimento da categoria Verduras, hortaliças e derivados, nome Coentro folhas desidratadas', 0, 309, 100, 20.9, 'Verduras, hortaliças e derivados', 'Coentro folhas desidratadas'),
(115, 4.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Couve manteiga crua', 0, 27, 100, 2.9, 'Verduras, hortaliças e derivados', 'Couve manteiga crua'),
(116, 8.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Couve manteiga refogada', 0, 90, 100, 1.7, 'Verduras, hortaliças e derivados', 'Couve manteiga refogada'),
(117, 4.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Couve-flor crua', 0, 23, 100, 1.9, 'Verduras, hortaliças e derivados', 'Couve-flor crua'),
(118, 3.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Couve-flor cozida', 0, 19, 100, 1.2, 'Verduras, hortaliças e derivados', 'Couve-flor cozida'),
(119, 2.6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Espinafre Nova Zelândia cru', 0, 16, 100, 2, 'Verduras, hortaliças e derivados', 'Espinafre Nova Zelândia cru'),
(120, 4.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Espinafre Nova Zelândia refogado', 0, 67, 100, 2.7, 'Verduras, hortaliças e derivados', 'Espinafre Nova Zelândia refogado'),
(121, 87.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Farinha de mandioca crua', 0, 361, 100, 1.6, 'Verduras, hortaliças e derivados', 'Farinha de mandioca crua'),
(122, 89.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Farinha de mandioca torrada', 0, 365, 100, 1.2, 'Verduras, hortaliças e derivados', 'Farinha de mandioca torrada'),
(123, 87.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Farinha de puba', 0, 360, 100, 1.6, 'Verduras, hortaliças e derivados', 'Farinha de puba'),
(124, 81.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Fécula de mandioca', 0, 331, 100, 0.5, 'Verduras, hortaliças e derivados', 'Fécula de mandioca'),
(125, 7.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Feijão broto cru', 0, 39, 100, 4.2, 'Verduras, hortaliças e derivados', 'Feijão broto cru'),
(126, 23.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Inhame cru', 0, 97, 100, 2.1, 'Verduras, hortaliças e derivados', 'Inhame cru'),
(127, 6.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Jiló cru', 0, 27, 100, 1.4, 'Verduras, hortaliças e derivados', 'Jiló cru'),
(128, 23.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Jurubeba crua', 0, 126, 100, 4.4, 'Verduras, hortaliças e derivados', 'Jurubeba crua'),
(129, 30.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Mandioca cozida', 0, 125, 100, 0.6, 'Verduras, hortaliças e derivados', 'Mandioca cozida'),
(130, 36.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Mandioca crua', 0, 151, 100, 1.1, 'Verduras, hortaliças e derivados', 'Mandioca crua'),
(131, 80.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Mandioca farofa temperada', 0, 406, 100, 2.1, 'Verduras, hortaliças e derivados', 'Mandioca farofa temperada'),
(132, 50.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Mandioca frita', 0, 300, 100, 1.4, 'Verduras, hortaliças e derivados', 'Mandioca frita'),
(133, 3.6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Manjericão cru', 0, 21, 100, 2, 'Verduras, hortaliças e derivados', 'Manjericão cru'),
(134, 2.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Maxixe cru', 0, 14, 100, 1.4, 'Verduras, hortaliças e derivados', 'Maxixe cru'),
(135, 3.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Mostarda folha crua', 0, 18, 100, 2.1, 'Verduras, hortaliças e derivados', 'Mostarda folha crua'),
(136, 36.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Nhoque batata cozido', 0, 181, 100, 5.9, 'Verduras, hortaliças e derivados', 'Nhoque batata cozido'),
(137, 4.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Nabo cru', 0, 18, 100, 1.2, 'Verduras, hortaliças e derivados', 'Nabo cru'),
(138, 4.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Palmito juçara em conserva', 0, 23, 100, 1.8, 'Verduras, hortaliças e derivados', 'Palmito juçara em conserva'),
(139, 5.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Palmito pupunha em conserva', 0, 29, 100, 2.5, 'Verduras, hortaliças e derivados', 'Palmito pupunha em conserva'),
(140, 34.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pão de queijo assado', 0, 363, 100, 5.1, 'Verduras, hortaliças e derivados', 'Pão de queijo assado'),
(141, 38.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pão de queijo cru', 0, 295, 100, 3.6, 'Verduras, hortaliças e derivados', 'Pão de queijo cru'),
(142, 2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pepino cru', 0, 10, 100, 0.9, 'Verduras, hortaliças e derivados', 'Pepino cru'),
(143, 6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pimentão amarelo cru', 0, 28, 100, 1.2, 'Verduras, hortaliças e derivados', 'Pimentão amarelo cru'),
(144, 4.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pimentão verde cru', 0, 21, 100, 1.1, 'Verduras, hortaliças e derivados', 'Pimentão verde cru'),
(145, 5.5, 'Alimento da categoria Verduras, hortaliças e derivados, nome Pimentão vermelho cru', 0, 23, 100, 1, 'Verduras, hortaliças e derivados', 'Pimentão vermelho cru'),
(146, 86.8, 'Alimento da categoria Verduras, hortaliças e derivados, nome Polvilho doce', 0, 351, 100, 0.4, 'Verduras, hortaliças e derivados', 'Polvilho doce'),
(147, 6.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Quiabo cru', 0, 30, 100, 1.9, 'Verduras, hortaliças e derivados', 'Quiabo cru'),
(148, 2.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Rabanete cru', 0, 14, 100, 1.4, 'Verduras, hortaliças e derivados', 'Rabanete cru'),
(149, 3.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Repolho branco cru', 0, 17, 100, 0.9, 'Verduras, hortaliças e derivados', 'Repolho branco cru'),
(150, 7.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Repolho roxo cru', 0, 31, 100, 1.9, 'Verduras, hortaliças e derivados', 'Repolho roxo cru'),
(151, 7.6, 'Alimento da categoria Verduras, hortaliças e derivados, nome Repolho roxo refogado', 0, 42, 100, 1.8, 'Verduras, hortaliças e derivados', 'Repolho roxo refogado'),
(152, 2.2, 'Alimento da categoria Verduras, hortaliças e derivados, nome Rúcula crua', 0, 13, 100, 1.8, 'Verduras, hortaliças e derivados', 'Rúcula crua'),
(153, 5.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Salsa crua', 0, 33, 100, 3.3, 'Verduras, hortaliças e derivados', 'Salsa crua'),
(154, 12.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Seleta de legumes enlatada', 0, 57, 100, 3.4, 'Verduras, hortaliças e derivados', 'Seleta de legumes enlatada'),
(155, 4.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Serralha crua', 0, 30, 100, 2.7, 'Verduras, hortaliças e derivados', 'Serralha crua'),
(156, 5.4, 'Alimento da categoria Verduras, hortaliças e derivados, nome Taioba crua', 0, 34, 100, 2.9, 'Verduras, hortaliças e derivados', 'Taioba crua'),
(157, 3.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Tomate com semente cru', 0, 15, 100, 1.1, 'Verduras, hortaliças e derivados', 'Tomate com semente cru'),
(158, 15, 'Alimento da categoria Verduras, hortaliças e derivados, nome Tomate extrato', 0, 61, 100, 2.4, 'Verduras, hortaliças e derivados', 'Tomate extrato'),
(159, 7.7, 'Alimento da categoria Verduras, hortaliças e derivados, nome Tomate molho industrializado', 0, 38, 100, 1.4, 'Verduras, hortaliças e derivados', 'Tomate molho industrializado'),
(160, 6.9, 'Alimento da categoria Verduras, hortaliças e derivados, nome Tomate purê', 0, 28, 100, 1.4, 'Verduras, hortaliças e derivados', 'Tomate purê'),
(161, 5.1, 'Alimento da categoria Verduras, hortaliças e derivados, nome Tomate salada', 0, 21, 100, 0.8, 'Verduras, hortaliças e derivados', 'Tomate salada'),
(162, 5.3, 'Alimento da categoria Verduras, hortaliças e derivados, nome Vagem crua', 0, 25, 100, 1.8, 'Verduras, hortaliças e derivados', 'Vagem crua'),
(163, 6, 'Alimento da categoria Frutas e derivados, nome Abacate cru', 0, 96, 100, 1.2, 'Frutas e derivados', 'Abacate cru'),
(164, 12.3, 'Alimento da categoria Frutas e derivados, nome Abacaxi cru', 0, 48, 100, 0.9, 'Frutas e derivados', 'Abacaxi cru'),
(165, 7.8, 'Alimento da categoria Frutas e derivados, nome Abacaxi polpa congelada', 0, 31, 100, 0.5, 'Frutas e derivados', 'Abacaxi polpa congelada'),
(166, 14.9, 'Alimento da categoria Frutas e derivados, nome Abiu cru', 0, 62, 100, 0.8, 'Frutas e derivados', 'Abiu cru'),
(167, 21.5, 'Alimento da categoria Frutas e derivados, nome Açaí polpa com xarope de guaraná e glucose', 0, 110, 100, 0.7, 'Frutas e derivados', 'Açaí polpa com xarope de guaraná e glucose'),
(168, 6.2, 'Alimento da categoria Frutas e derivados, nome Açaí polpa congelada', 0, 58, 100, 0.8, 'Frutas e derivados', 'Açaí polpa congelada'),
(169, 8, 'Alimento da categoria Frutas e derivados, nome Acerola crua', 0, 33, 100, 0.9, 'Frutas e derivados', 'Acerola crua'),
(170, 5.5, 'Alimento da categoria Frutas e derivados, nome Acerola polpa congelada', 0, 22, 100, 0.6, 'Frutas e derivados', 'Acerola polpa congelada'),
(171, 46.9, 'Alimento da categoria Frutas e derivados, nome Ameixa calda enlatada', 0, 183, 100, 0.4, 'Frutas e derivados', 'Ameixa calda enlatada'),
(172, 13.9, 'Alimento da categoria Frutas e derivados, nome Ameixa crua', 0, 53, 100, 0.8, 'Frutas e derivados', 'Ameixa crua'),
(173, 47.7, 'Alimento da categoria Frutas e derivados, nome Ameixa em calda enlatada drenada', 0, 177, 100, 1, 'Frutas e derivados', 'Ameixa em calda enlatada drenada'),
(174, 25.3, 'Alimento da categoria Frutas e derivados, nome Atemóia crua', 0, 97, 100, 1, 'Frutas e derivados', 'Atemóia crua'),
(175, 33.7, 'Alimento da categoria Frutas e derivados, nome Banana da terra crua', 0, 128, 100, 1.4, 'Frutas e derivados', 'Banana da terra crua'),
(176, 75.7, 'Alimento da categoria Frutas e derivados, nome Banana doce em barra', 0, 280, 100, 2.2, 'Frutas e derivados', 'Banana doce em barra'),
(177, 27.8, 'Alimento da categoria Frutas e derivados, nome Banana figo crua', 0, 105, 100, 1.1, 'Frutas e derivados', 'Banana figo crua'),
(178, 22.3, 'Alimento da categoria Frutas e derivados, nome Banana maçã crua', 0, 87, 100, 1.8, 'Frutas e derivados', 'Banana maçã crua'),
(179, 23.8, 'Alimento da categoria Frutas e derivados, nome Banana nanica crua', 0, 92, 100, 1.4, 'Frutas e derivados', 'Banana nanica crua'),
(180, 29.3, 'Alimento da categoria Frutas e derivados, nome Banana ouro crua', 0, 112, 100, 1.5, 'Frutas e derivados', 'Banana ouro crua'),
(181, 20.3, 'Alimento da categoria Frutas e derivados, nome Banana pacova crua', 0, 78, 100, 1.2, 'Frutas e derivados', 'Banana pacova crua'),
(182, 26, 'Alimento da categoria Frutas e derivados, nome Banana prata crua', 0, 98, 100, 1.3, 'Frutas e derivados', 'Banana prata crua'),
(183, 19.4, 'Alimento da categoria Frutas e derivados, nome Cacau cru', 0, 74, 100, 1, 'Frutas e derivados', 'Cacau cru'),
(184, 11.4, 'Alimento da categoria Frutas e derivados, nome Cajá-Manga cru', 0, 46, 100, 1.3, 'Frutas e derivados', 'Cajá-Manga cru'),
(185, 6.4, 'Alimento da categoria Frutas e derivados, nome Cajá polpa congelada', 0, 26, 100, 0.6, 'Frutas e derivados', 'Cajá polpa congelada'),
(186, 10.3, 'Alimento da categoria Frutas e derivados, nome Caju cru', 0, 43, 100, 1, 'Frutas e derivados', 'Caju cru'),
(187, 9.4, 'Alimento da categoria Frutas e derivados, nome Caju polpa congelada', 0, 37, 100, 0.5, 'Frutas e derivados', 'Caju polpa congelada'),
(188, 10.7, 'Alimento da categoria Frutas e derivados, nome Caju suco concentrado envasado', 0, 45, 100, 0.4, 'Frutas e derivados', 'Caju suco concentrado envasado'),
(189, 19.3, 'Alimento da categoria Frutas e derivados, nome Caqui chocolate cru', 0, 71, 100, 0.4, 'Frutas e derivados', 'Caqui chocolate cru'),
(190, 11.5, 'Alimento da categoria Frutas e derivados, nome Carambola crua', 0, 46, 100, 0.9, 'Frutas e derivados', 'Carambola crua'),
(191, 18.9, 'Alimento da categoria Frutas e derivados, nome Ciriguela crua', 0, 76, 100, 1.4, 'Frutas e derivados', 'Ciriguela crua'),
(192, 10.4, 'Alimento da categoria Frutas e derivados, nome Cupuaçu cru', 0, 49, 100, 1.2, 'Frutas e derivados', 'Cupuaçu cru'),
(193, 11.4, 'Alimento da categoria Frutas e derivados, nome Cupuaçu polpa congelada', 0, 49, 100, 0.8, 'Frutas e derivados', 'Cupuaçu polpa congelada'),
(194, 10.2, 'Alimento da categoria Frutas e derivados, nome Figo cru', 0, 41, 100, 1, 'Frutas e derivados', 'Figo cru'),
(195, 50.3, 'Alimento da categoria Frutas e derivados, nome Figo enlatado em calda', 0, 184, 100, 0.6, 'Frutas e derivados', 'Figo enlatado em calda'),
(196, 17.2, 'Alimento da categoria Frutas e derivados, nome Fruta-pão crua', 0, 67, 100, 1.1, 'Frutas e derivados', 'Fruta-pão crua'),
(197, 12.4, 'Alimento da categoria Frutas e derivados, nome Goiaba branca com casca crua', 0, 52, 100, 0.9, 'Frutas e derivados', 'Goiaba branca com casca crua'),
(198, 74.1, 'Alimento da categoria Frutas e derivados, nome Goiaba doce em pasta', 0, 269, 100, 0.6, 'Frutas e derivados', 'Goiaba doce em pasta'),
(199, 78.7, 'Alimento da categoria Frutas e derivados, nome Goiaba doce cascão', 0, 286, 100, 0.4, 'Frutas e derivados', 'Goiaba doce cascão'),
(200, 13, 'Alimento da categoria Frutas e derivados, nome Goiaba vermelha com casca crua', 0, 54, 100, 1.1, 'Frutas e derivados', 'Goiaba vermelha com casca crua'),
(201, 15.8, 'Alimento da categoria Frutas e derivados, nome Graviola crua', 0, 62, 100, 0.8, 'Frutas e derivados', 'Graviola crua'),
(202, 9.8, 'Alimento da categoria Frutas e derivados, nome Graviola polpa congelada', 0, 38, 100, 0.6, 'Frutas e derivados', 'Graviola polpa congelada'),
(203, 15.3, 'Alimento da categoria Frutas e derivados, nome Jabuticaba crua', 0, 58, 100, 0.6, 'Frutas e derivados', 'Jabuticaba crua'),
(204, 22.5, 'Alimento da categoria Frutas e derivados, nome Jaca crua', 0, 88, 100, 1.4, 'Frutas e derivados', 'Jaca crua'),
(205, 6.5, 'Alimento da categoria Frutas e derivados, nome Jambo cru', 0, 27, 100, 0.9, 'Frutas e derivados', 'Jambo cru'),
(206, 10.6, 'Alimento da categoria Frutas e derivados, nome Jamelão cru', 0, 41, 100, 0.5, 'Frutas e derivados', 'Jamelão cru'),
(207, 11.5, 'Alimento da categoria Frutas e derivados, nome Kiwi cru', 0, 51, 100, 1.3, 'Frutas e derivados', 'Kiwi cru'),
(208, 11.5, 'Alimento da categoria Frutas e derivados, nome Laranja baía crua', 0, 45, 100, 1, 'Frutas e derivados', 'Laranja baía crua'),
(209, 8.7, 'Alimento da categoria Frutas e derivados, nome Laranja baía suco', 0, 37, 100, 0.7, 'Frutas e derivados', 'Laranja baía suco'),
(210, 12.9, 'Alimento da categoria Frutas e derivados, nome Laranja da terra crua', 0, 51, 100, 1.1, 'Frutas e derivados', 'Laranja da terra crua'),
(211, 9.6, 'Alimento da categoria Frutas e derivados, nome Laranja da terra suco', 0, 41, 100, 0.7, 'Frutas e derivados', 'Laranja da terra suco'),
(212, 11.5, 'Alimento da categoria Frutas e derivados, nome Laranja lima crua', 0, 46, 100, 1.1, 'Frutas e derivados', 'Laranja lima crua'),
(213, 9.2, 'Alimento da categoria Frutas e derivados, nome Laranja lima suco', 0, 39, 100, 0.7, 'Frutas e derivados', 'Laranja lima suco'),
(214, 8.9, 'Alimento da categoria Frutas e derivados, nome Laranja pêra crua', 0, 37, 100, 1, 'Frutas e derivados', 'Laranja pêra crua'),
(215, 7.6, 'Alimento da categoria Frutas e derivados, nome Laranja pêra suco', 0, 33, 100, 0.7, 'Frutas e derivados', 'Laranja pêra suco'),
(216, 11.7, 'Alimento da categoria Frutas e derivados, nome Laranja valência crua', 0, 46, 100, 0.8, 'Frutas e derivados', 'Laranja valência crua'),
(217, 8.6, 'Alimento da categoria Frutas e derivados, nome Laranja valência suco', 0, 36, 100, 0.5, 'Frutas e derivados', 'Laranja valência suco'),
(218, 5.2, 'Alimento da categoria Frutas e derivados, nome Limão cravo suco', 0, 14, 100, 0.3, 'Frutas e derivados', 'Limão cravo suco'),
(219, 7.3, 'Alimento da categoria Frutas e derivados, nome Limão galego suco', 0, 22, 100, 0.6, 'Frutas e derivados', 'Limão galego suco'),
(220, 11.1, 'Alimento da categoria Frutas e derivados, nome Limão tahiti cru', 0, 32, 100, 0.9, 'Frutas e derivados', 'Limão tahiti cru'),
(221, 16.6, 'Alimento da categoria Frutas e derivados, nome Maçã Argentina com casca crua', 0, 63, 100, 0.2, 'Frutas e derivados', 'Maçã Argentina com casca crua'),
(222, 15.2, 'Alimento da categoria Frutas e derivados, nome Maçã Fuji com casca crua', 0, 56, 100, 0.3, 'Frutas e derivados', 'Maçã Fuji com casca crua'),
(223, 13.9, 'Alimento da categoria Frutas e derivados, nome Macaúba crua', 0, 404, 100, 2.1, 'Frutas e derivados', 'Macaúba crua'),
(224, 54, 'Alimento da categoria Frutas e derivados, nome Mamão doce em calda drenado', 0, 196, 100, 0.2, 'Frutas e derivados', 'Mamão doce em calda drenado'),
(225, 11.6, 'Alimento da categoria Frutas e derivados, nome Mamão Formosa cru', 0, 45, 100, 0.8, 'Frutas e derivados', 'Mamão Formosa cru'),
(226, 10.4, 'Alimento da categoria Frutas e derivados, nome Mamão Papaia cru', 0, 40, 100, 0.5, 'Frutas e derivados', 'Mamão Papaia cru'),
(227, 57.6, 'Alimento da categoria Frutas e derivados, nome Mamão verde doce em calda drenado', 0, 209, 100, 0.3, 'Frutas e derivados', 'Mamão verde doce em calda drenado'),
(228, 16.7, 'Alimento da categoria Frutas e derivados, nome Manga Haden crua', 0, 64, 100, 0.4, 'Frutas e derivados', 'Manga Haden crua'),
(229, 19.4, 'Alimento da categoria Frutas e derivados, nome Manga Palmer crua', 0, 72, 100, 0.4, 'Frutas e derivados', 'Manga Palmer crua'),
(230, 12.5, 'Alimento da categoria Frutas e derivados, nome Manga polpa congelada', 0, 48, 100, 0.4, 'Frutas e derivados', 'Manga polpa congelada'),
(231, 12.8, 'Alimento da categoria Frutas e derivados, nome Manga Tommy Atkins crua', 0, 51, 100, 0.9, 'Frutas e derivados', 'Manga Tommy Atkins crua'),
(232, 12.3, 'Alimento da categoria Frutas e derivados, nome Maracujá cru', 0, 68, 100, 2, 'Frutas e derivados', 'Maracujá cru'),
(233, 9.6, 'Alimento da categoria Frutas e derivados, nome Maracujá polpa congelada', 0, 39, 100, 0.8, 'Frutas e derivados', 'Maracujá polpa congelada'),
(234, 9.6, 'Alimento da categoria Frutas e derivados, nome Maracujá suco concentrado envasado', 0, 42, 100, 0.8, 'Frutas e derivados', 'Maracujá suco concentrado envasado'),
(235, 8.1, 'Alimento da categoria Frutas e derivados, nome Melancia crua', 0, 33, 100, 0.9, 'Frutas e derivados', 'Melancia crua'),
(236, 7.5, 'Alimento da categoria Frutas e derivados, nome Melão cru', 0, 29, 100, 0.7, 'Frutas e derivados', 'Melão cru'),
(237, 14.9, 'Alimento da categoria Frutas e derivados, nome Mexerica Murcote crua', 0, 58, 100, 0.9, 'Frutas e derivados', 'Mexerica Murcote crua'),
(238, 9.3, 'Alimento da categoria Frutas e derivados, nome Mexerica Rio crua', 0, 37, 100, 0.7, 'Frutas e derivados', 'Mexerica Rio crua'),
(239, 6.8, 'Alimento da categoria Frutas e derivados, nome Morango cru', 0, 30, 100, 0.9, 'Frutas e derivados', 'Morango cru'),
(240, 11.5, 'Alimento da categoria Frutas e derivados, nome Nêspera crua', 0, 43, 100, 0.3, 'Frutas e derivados', 'Nêspera crua'),
(241, 13, 'Alimento da categoria Frutas e derivados, nome Pequi cru', 0, 205, 100, 2.3, 'Frutas e derivados', 'Pequi cru'),
(242, 16.1, 'Alimento da categoria Frutas e derivados, nome Pêra Park crua', 0, 61, 100, 0.2, 'Frutas e derivados', 'Pêra Park crua'),
(243, 14, 'Alimento da categoria Frutas e derivados, nome Pêra Williams crua', 0, 53, 100, 0.6, 'Frutas e derivados', 'Pêra Williams crua'),
(244, 9.3, 'Alimento da categoria Frutas e derivados, nome Pêssego Aurora cru', 0, 36, 100, 0.8, 'Frutas e derivados', 'Pêssego Aurora cru'),
(245, 16.9, 'Alimento da categoria Frutas e derivados, nome Pêssego enlatado em calda', 0, 63, 100, 0.7, 'Frutas e derivados', 'Pêssego enlatado em calda'),
(246, 22.4, 'Alimento da categoria Frutas e derivados, nome Pinha crua', 0, 88, 100, 1.5, 'Frutas e derivados', 'Pinha crua'),
(247, 10.2, 'Alimento da categoria Frutas e derivados, nome Pitanga crua', 0, 41, 100, 0.9, 'Frutas e derivados', 'Pitanga crua'),
(248, 4.8, 'Alimento da categoria Frutas e derivados, nome Pitanga polpa congelada', 0, 19, 100, 0.3, 'Frutas e derivados', 'Pitanga polpa congelada'),
(249, 15.1, 'Alimento da categoria Frutas e derivados, nome Romã crua', 0, 56, 100, 0.4, 'Frutas e derivados', 'Romã crua'),
(250, 72.5, 'Alimento da categoria Frutas e derivados, nome Tamarindo cru', 0, 276, 100, 3.2, 'Frutas e derivados', 'Tamarindo cru'),
(251, 9.6, 'Alimento da categoria Frutas e derivados, nome Tangerina Poncã crua', 0, 38, 100, 0.8, 'Frutas e derivados', 'Tangerina Poncã crua'),
(252, 8.8, 'Alimento da categoria Frutas e derivados, nome Tangerina Poncã suco', 0, 36, 100, 0.5, 'Frutas e derivados', 'Tangerina Poncã suco'),
(253, 26.5, 'Alimento da categoria Frutas e derivados, nome Tucumã cru', 0, 262, 100, 2.1, 'Frutas e derivados', 'Tucumã cru'),
(254, 9.4, 'Alimento da categoria Frutas e derivados, nome Umbu cru', 0, 37, 100, 0.8, 'Frutas e derivados', 'Umbu cru'),
(255, 8.8, 'Alimento da categoria Frutas e derivados, nome Umbu polpa congelada', 0, 34, 100, 0.5, 'Frutas e derivados', 'Umbu polpa congelada'),
(256, 13.6, 'Alimento da categoria Frutas e derivados, nome Uva Itália crua', 0, 53, 100, 0.7, 'Frutas e derivados', 'Uva Itália crua'),
(257, 12.7, 'Alimento da categoria Frutas e derivados, nome Uva Rubi crua', 0, 49, 100, 0.6, 'Frutas e derivados', 'Uva Rubi crua'),
(258, 14.7, 'Alimento da categoria Frutas e derivados, nome Uva suco concentrado envasado', 0, 58, 100, 0, 'Frutas e derivados', 'Uva suco concentrado envasado'),
(259, 0.1, 'Alimento da categoria Gorduras e óleos, nome Azeite de dendê', 0, 884, 100, 0.4, 'Gorduras e óleos', 'Azeite de dendê'),
(262, 0, 'Alimento da categoria Gorduras e óleos, nome Manteiga sem sal', 0, 758, 100, 0.4, 'Gorduras e óleos', 'Manteiga sem sal'),
(263, 0, 'Alimento da categoria Gorduras e óleos, nome Margarina com óleo hidrogenado com sal (65% de lipídeos)', 0, 596, 100, 0, 'Gorduras e óleos', 'Margarina com óleo hidrogenado com sal (65% de lipídeos)'),
(264, 0, 'Alimento da categoria Gorduras e óleos, nome Margarina com óleo hidrogenado sem sal (80% de lipídeos)', 0, 723, 100, 0, 'Gorduras e óleos', 'Margarina com óleo hidrogenado sem sal (80% de lipídeos)'),
(265, 0, 'Alimento da categoria Gorduras e óleos, nome Margarina com óleo interesterificado com sal (65%de lipídeos)', 0, 594, 100, 0, 'Gorduras e óleos', 'Margarina com óleo interesterificado com sal (65%de lipídeos)'),
(266, 0, 'Alimento da categoria Gorduras e óleos, nome Margarina com óleo interesterificado sem sal (65% de lipídeos)', 0, 593, 100, 0, 'Gorduras e óleos', 'Margarina com óleo interesterificado sem sal (65% de lipídeos)'),
(267, 0, 'Alimento da categoria Gorduras e óleos, nome Óleo de babaçu', 0, 884, 100, 23.5, 'Gorduras e óleos', 'Óleo de babaçu'),
(274, 0, 'Alimento da categoria Pescados e frutos do mar, nome Abadejo filé congeladocozido', 0, 91, 100, 19.3, 'Pescados e frutos do mar', 'Abadejo filé congeladocozido'),
(275, 0, 'Alimento da categoria Pescados e frutos do mar, nome Abadejo filé congelado cru', 0, 59, 100, 13.1, 'Pescados e frutos do mar', 'Abadejo filé congelado cru'),
(276, 0, 'Alimento da categoria Pescados e frutos do mar, nome Abadejo filé congelado grelhado', 0, 130, 100, 27.6, 'Pescados e frutos do mar', 'Abadejo filé congelado grelhado'),
(277, 0, 'Alimento da categoria Pescados e frutos do mar, nome Atum conserva em óleo', 0, 166, 100, 26.2, 'Pescados e frutos do mar', 'Atum conserva em óleo'),
(278, 0, 'Alimento da categoria Pescados e frutos do mar, nome Atum fresco cru', 0, 118, 100, 25.7, 'Pescados e frutos do mar', 'Atum fresco cru'),
(279, 0, 'Alimento da categoria Pescados e frutos do mar, nome Bacalhau salgado cru', 0, 136, 100, 29, 'Pescados e frutos do mar', 'Bacalhau salgado cru'),
(280, 1.2, 'Alimento da categoria Pescados e frutos do mar, nome Bacalhau salgado refogado', 0, 140, 100, 24, 'Pescados e frutos do mar', 'Bacalhau salgado refogado'),
(281, 3.1, 'Alimento da categoria Pescados e frutos do mar, nome Cação posta com farinha de trigo frita', 0, 208, 100, 25, 'Pescados e frutos do mar', 'Cação posta com farinha de trigo frita'),
(282, 0, 'Alimento da categoria Pescados e frutos do mar, nome Cação posta cozida', 0, 116, 100, 25.6, 'Pescados e frutos do mar', 'Cação posta cozida'),
(283, 0, 'Alimento da categoria Pescados e frutos do mar, nome Cação posta crua', 0, 83, 100, 17.9, 'Pescados e frutos do mar', 'Cação posta crua'),
(284, 0, 'Alimento da categoria Pescados e frutos do mar, nome Camarão Rio Grande grande cozido', 0, 90, 100, 19, 'Pescados e frutos do mar', 'Camarão Rio Grande grande cozido'),
(285, 0, 'Alimento da categoria Pescados e frutos do mar, nome Camarão Rio Grande grande cru', 0, 47, 100, 10, 'Pescados e frutos do mar', 'Camarão Rio Grande grande cru'),
(286, 2.9, 'Alimento da categoria Pescados e frutos do mar, nome Camarão Sete Barbas sem cabeça com casca frito', 0, 231, 100, 18.4, 'Pescados e frutos do mar', 'Camarão Sete Barbas sem cabeça com casca frito'),
(287, 0, 'Alimento da categoria Pescados e frutos do mar, nome Caranguejo cozido', 0, 83, 100, 18.5, 'Pescados e frutos do mar', 'Caranguejo cozido'),
(288, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corimba cru', 0, 128, 100, 17.4, 'Pescados e frutos do mar', 'Corimba cru'),
(289, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corimbatá assado', 0, 261, 100, 19.9, 'Pescados e frutos do mar', 'Corimbatá assado'),
(290, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corimbatá cozido', 0, 239, 100, 20.1, 'Pescados e frutos do mar', 'Corimbatá cozido'),
(291, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corvina de água doce crua', 0, 101, 100, 18.9, 'Pescados e frutos do mar', 'Corvina de água doce crua'),
(292, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corvina do mar crua', 0, 94, 100, 18.6, 'Pescados e frutos do mar', 'Corvina do mar crua'),
(293, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corvina grande assada', 0, 147, 100, 26.8, 'Pescados e frutos do mar', 'Corvina grande assada'),
(294, 0, 'Alimento da categoria Pescados e frutos do mar, nome Corvina grande cozida', 0, 100, 100, 23.4, 'Pescados e frutos do mar', 'Corvina grande cozida'),
(295, 0, 'Alimento da categoria Pescados e frutos do mar, nome Dourada de água doce fresca', 0, 131, 100, 18.8, 'Pescados e frutos do mar', 'Dourada de água doce fresca'),
(296, 0, 'Alimento da categoria Pescados e frutos do mar, nome Lambari congelado cru', 0, 131, 100, 16.8, 'Pescados e frutos do mar', 'Lambari congelado cru'),
(297, 0, 'Alimento da categoria Pescados e frutos do mar, nome Lambari congelado frito', 0, 327, 100, 28.4, 'Pescados e frutos do mar', 'Lambari congelado frito'),
(298, 0, 'Alimento da categoria Pescados e frutos do mar, nome Lambari fresco cru', 0, 152, 100, 15.7, 'Pescados e frutos do mar', 'Lambari fresco cru'),
(299, 10.2, 'Alimento da categoria Pescados e frutos do mar, nome Manjuba com farinha de trigo frita', 0, 344, 100, 23.5, 'Pescados e frutos do mar', 'Manjuba com farinha de trigo frita'),
(300, 0, 'Alimento da categoria Pescados e frutos do mar, nome Manjuba frita', 0, 349, 100, 30.1, 'Pescados e frutos do mar', 'Manjuba frita'),
(301, 0, 'Alimento da categoria Pescados e frutos do mar, nome Merluza filé assado', 0, 122, 100, 26.6, 'Pescados e frutos do mar', 'Merluza filé assado'),
(302, 0, 'Alimento da categoria Pescados e frutos do mar, nome Merluza filé cru', 0, 89, 100, 16.6, 'Pescados e frutos do mar', 'Merluza filé cru'),
(303, 0, 'Alimento da categoria Pescados e frutos do mar, nome Merluza filé frito', 0, 192, 100, 26.9, 'Pescados e frutos do mar', 'Merluza filé frito'),
(304, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pescada branca crua', 0, 111, 100, 16.3, 'Pescados e frutos do mar', 'Pescada branca crua'),
(305, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pescada branca frita', 0, 223, 100, 27.4, 'Pescados e frutos do mar', 'Pescada branca frita'),
(306, 5, 'Alimento da categoria Pescados e frutos do mar, nome Pescada filé com farinha de trigo frito', 0, 283, 100, 21.4, 'Pescados e frutos do mar', 'Pescada filé com farinha de trigo frito'),
(307, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pescada filé cru', 0, 107, 100, 16.7, 'Pescados e frutos do mar', 'Pescada filé cru'),
(308, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pescada filé frito', 0, 154, 100, 28.6, 'Pescados e frutos do mar', 'Pescada filé frito'),
(309, 5, 'Alimento da categoria Pescados e frutos do mar, nome Pescada filé molho escabeche', 0, 142, 100, 11.8, 'Pescados e frutos do mar', 'Pescada filé molho escabeche'),
(310, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pescadinha crua', 0, 76, 100, 15.5, 'Pescados e frutos do mar', 'Pescadinha crua'),
(311, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pintado assado', 0, 192, 100, 36.5, 'Pescados e frutos do mar', 'Pintado assado'),
(312, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pintado cru', 0, 91, 100, 18.6, 'Pescados e frutos do mar', 'Pintado cru'),
(313, 0, 'Alimento da categoria Pescados e frutos do mar, nome Pintado grelhado', 0, 152, 100, 30.8, 'Pescados e frutos do mar', 'Pintado grelhado'),
(314, 0, 'Alimento da categoria Pescados e frutos do mar, nome Porquinho cru', 0, 93, 100, 20.5, 'Pescados e frutos do mar', 'Porquinho cru'),
(315, 0, 'Alimento da categoria Pescados e frutos do mar, nome Salmão filé com pele fresco  grelhado', 0, 229, 100, 23.9, 'Pescados e frutos do mar', 'Salmão filé com pele fresco  grelhado'),
(316, 0, 'Alimento da categoria Pescados e frutos do mar, nome Salmão sem pele fresco cru', 0, 170, 100, 19.3, 'Pescados e frutos do mar', 'Salmão sem pele fresco cru'),
(317, 0, 'Alimento da categoria Pescados e frutos do mar, nome Salmão sem pele fresco grelhado', 0, 243, 100, 26.1, 'Pescados e frutos do mar', 'Salmão sem pele fresco grelhado'),
(318, 0, 'Alimento da categoria Pescados e frutos do mar, nome Sardinha assada', 0, 164, 100, 32.2, 'Pescados e frutos do mar', 'Sardinha assada'),
(319, 0, 'Alimento da categoria Pescados e frutos do mar, nome Sardinha conserva em óleo', 0, 285, 100, 15.9, 'Pescados e frutos do mar', 'Sardinha conserva em óleo'),
(320, 0, 'Alimento da categoria Pescados e frutos do mar, nome Sardinha frita', 0, 257, 100, 33.4, 'Pescados e frutos do mar', 'Sardinha frita'),
(321, 0, 'Alimento da categoria Pescados e frutos do mar, nome Sardinha inteira crua', 0, 114, 100, 21.1, 'Pescados e frutos do mar', 'Sardinha inteira crua'),
(322, 0, 'Alimento da categoria Pescados e frutos do mar, nome Tucunaré filé congelado cru', 0, 88, 100, 18, 'Pescados e frutos do mar', 'Tucunaré filé congelado cru'),
(323, 2.9, 'Alimento da categoria Carnes e derivados, nome Apresuntado', 0, 129, 100, 13.5, 'Carnes e derivados', 'Apresuntado'),
(324, 15.1, 'Alimento da categoria Carnes e derivados, nome Caldo de carne tablete', 0, 241, 100, 7.8, 'Carnes e derivados', 'Caldo de carne tablete'),
(325, 10.6, 'Alimento da categoria Carnes e derivados, nome Caldo de galinha tablete', 0, 251, 100, 6.3, 'Carnes e derivados', 'Caldo de galinha tablete'),
(326, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina acém moído cozido', 0, 212, 100, 26.7, 'Carnes e derivados', 'Carne bovina acém moído cozido'),
(327, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina acém moído cru', 0, 137, 100, 19.4, 'Carnes e derivados', 'Carne bovina acém moído cru'),
(328, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina acém sem gordura cozido', 0, 215, 100, 27.3, 'Carnes e derivados', 'Carne bovina acém sem gordura cozido'),
(329, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina acém sem gordura cru', 0, 144, 100, 20.8, 'Carnes e derivados', 'Carne bovina acém sem gordura cru'),
(330, 9.8, 'Alimento da categoria Carnes e derivados, nome Carne bovina almôndegas cruas', 0, 189, 100, 12.3, 'Carnes e derivados', 'Carne bovina almôndegas cruas'),
(331, 14.3, 'Alimento da categoria Carnes e derivados, nome Carne bovina almôndegas fritas', 0, 272, 100, 18.2, 'Carnes e derivados', 'Carne bovina almôndegas fritas'),
(332, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina bucho cozido', 0, 133, 100, 21.6, 'Carnes e derivados', 'Carne bovina bucho cozido'),
(333, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina bucho cru', 0, 137, 100, 20.5, 'Carnes e derivados', 'Carne bovina bucho cru'),
(334, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina capa de contra-filé com gordura crua', 0, 217, 100, 19.2, 'Carnes e derivados', 'Carne bovina capa de contra-filé com gordura crua'),
(335, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina capa de contra-filé com gordura grelhada', 0, 312, 100, 30.7, 'Carnes e derivados', 'Carne bovina capa de contra-filé com gordura grelhada'),
(336, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina capa de contra-filé sem gordura crua', 0, 131, 100, 21.5, 'Carnes e derivados', 'Carne bovina capa de contra-filé sem gordura crua'),
(337, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina capa de contra-filé sem gordura grelhada', 0, 239, 100, 35.1, 'Carnes e derivados', 'Carne bovina capa de contra-filé sem gordura grelhada'),
(338, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina charque cozido', 0, 263, 100, 36.4, 'Carnes e derivados', 'Carne bovina charque cozido'),
(339, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina charque cru', 0, 249, 100, 22.7, 'Carnes e derivados', 'Carne bovina charque cru'),
(340, 12.2, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé à milanesa', 0, 352, 100, 20.6, 'Carnes e derivados', 'Carne bovina contra-filé à milanesa'),
(341, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé de costela cru', 0, 202, 100, 19.8, 'Carnes e derivados', 'Carne bovina contra-filé de costela cru'),
(342, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé de costela grelhado', 0, 275, 100, 29.9, 'Carnes e derivados', 'Carne bovina contra-filé de costela grelhado'),
(343, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé com gordura cru', 0, 206, 100, 21.2, 'Carnes e derivados', 'Carne bovina contra-filé com gordura cru'),
(344, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé com gordura grelhado', 0, 278, 100, 32.4, 'Carnes e derivados', 'Carne bovina contra-filé com gordura grelhado'),
(345, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé sem gordura cru', 0, 157, 100, 24, 'Carnes e derivados', 'Carne bovina contra-filé sem gordura cru'),
(346, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina contra-filé sem gordura grelhado', 0, 194, 100, 35.9, 'Carnes e derivados', 'Carne bovina contra-filé sem gordura grelhado'),
(347, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina costela assada', 0, 373, 100, 28.8, 'Carnes e derivados', 'Carne bovina costela assada'),
(348, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina costela crua', 0, 358, 100, 16.7, 'Carnes e derivados', 'Carne bovina costela crua'),
(349, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina coxão duro sem gordura cozido', 0, 217, 100, 31.9, 'Carnes e derivados', 'Carne bovina coxão duro sem gordura cozido'),
(350, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina coxão duro sem gordura cru', 0, 148, 100, 21.5, 'Carnes e derivados', 'Carne bovina coxão duro sem gordura cru'),
(351, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina coxão mole sem gordura cozido', 0, 219, 100, 32.4, 'Carnes e derivados', 'Carne bovina coxão mole sem gordura cozido'),
(352, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina coxão mole sem gordura cru', 0, 169, 100, 21.2, 'Carnes e derivados', 'Carne bovina coxão mole sem gordura cru'),
(353, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina cupim assado', 0, 330, 100, 28.6, 'Carnes e derivados', 'Carne bovina cupim assado'),
(354, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina cupim cru', 0, 221, 100, 19.5, 'Carnes e derivados', 'Carne bovina cupim cru'),
(355, 1.1, 'Alimento da categoria Carnes e derivados, nome Carne bovina fígado cru', 0, 141, 100, 20.7, 'Carnes e derivados', 'Carne bovina fígado cru'),
(356, 4.2, 'Alimento da categoria Carnes e derivados, nome Carne bovina fígado grelhado', 0, 225, 100, 29.9, 'Carnes e derivados', 'Carne bovina fígado grelhado'),
(357, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina filé mingnon sem gordura cru', 0, 143, 100, 21.6, 'Carnes e derivados', 'Carne bovina filé mingnon sem gordura cru'),
(358, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina filé mingnon sem gordura grelhado', 0, 220, 100, 32.8, 'Carnes e derivados', 'Carne bovina filé mingnon sem gordura grelhado'),
(359, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina flanco sem gordura cozido', 0, 196, 100, 29.4, 'Carnes e derivados', 'Carne bovina flanco sem gordura cozido'),
(360, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina flanco sem gordura cru', 0, 141, 100, 20, 'Carnes e derivados', 'Carne bovina flanco sem gordura cru'),
(361, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina fraldinha com gordura cozida', 0, 338, 100, 24.2, 'Carnes e derivados', 'Carne bovina fraldinha com gordura cozida'),
(362, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina fraldinha com gordura crua', 0, 221, 100, 17.6, 'Carnes e derivados', 'Carne bovina fraldinha com gordura crua'),
(363, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina lagarto cozido', 0, 222, 100, 32.9, 'Carnes e derivados', 'Carne bovina lagarto cozido'),
(364, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina lagarto cru', 0, 135, 100, 20.5, 'Carnes e derivados', 'Carne bovina lagarto cru'),
(365, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina língua cozida', 0, 315, 100, 21.4, 'Carnes e derivados', 'Carne bovina língua cozida'),
(366, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina língua crua', 0, 215, 100, 17.1, 'Carnes e derivados', 'Carne bovina língua crua'),
(367, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina maminha crua', 0, 153, 100, 20.9, 'Carnes e derivados', 'Carne bovina maminha crua'),
(368, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina maminha grelhada', 0, 153, 100, 30.7, 'Carnes e derivados', 'Carne bovina maminha grelhada'),
(369, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina miolo de alcatra sem gordura cru', 0, 163, 100, 21.6, 'Carnes e derivados', 'Carne bovina miolo de alcatra sem gordura cru'),
(370, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina miolo de alcatra sem gordura grelhado', 0, 241, 100, 31.9, 'Carnes e derivados', 'Carne bovina miolo de alcatra sem gordura grelhado'),
(371, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina músculo sem gordura cozido', 0, 194, 100, 31.2, 'Carnes e derivados', 'Carne bovina músculo sem gordura cozido'),
(372, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina músculo sem gordura cru', 0, 142, 100, 21.6, 'Carnes e derivados', 'Carne bovina músculo sem gordura cru'),
(373, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina paleta com gordura crua', 0, 159, 100, 21.4, 'Carnes e derivados', 'Carne bovina paleta com gordura crua'),
(374, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina paleta sem gordura cozida', 0, 194, 100, 29.7, 'Carnes e derivados', 'Carne bovina paleta sem gordura cozida'),
(375, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina paleta sem gordura crua', 0, 141, 100, 21, 'Carnes e derivados', 'Carne bovina paleta sem gordura crua'),
(376, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina patinho sem gordura cru', 0, 133, 100, 21.7, 'Carnes e derivados', 'Carne bovina patinho sem gordura cru'),
(377, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina patinho sem gordura grelhado', 0, 219, 100, 35.9, 'Carnes e derivados', 'Carne bovina patinho sem gordura grelhado'),
(378, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina peito sem gordura cozido', 0, 338, 100, 22.2, 'Carnes e derivados', 'Carne bovina peito sem gordura cozido'),
(379, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina peito sem gordura cru', 0, 259, 100, 17.6, 'Carnes e derivados', 'Carne bovina peito sem gordura cru'),
(380, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina picanha com gordura crua', 0, 213, 100, 18.8, 'Carnes e derivados', 'Carne bovina picanha com gordura crua'),
(381, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina picanha com gordura grelhada', 0, 289, 100, 26.4, 'Carnes e derivados', 'Carne bovina picanha com gordura grelhada'),
(382, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina picanha sem gordura crua', 0, 134, 100, 21.3, 'Carnes e derivados', 'Carne bovina picanha sem gordura crua'),
(383, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina picanha sem gordura grelhada', 0, 238, 100, 31.9, 'Carnes e derivados', 'Carne bovina picanha sem gordura grelhada'),
(384, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina seca cozida', 0, 313, 100, 26.9, 'Carnes e derivados', 'Carne bovina seca cozida'),
(385, 0, 'Alimento da categoria Carnes e derivados, nome Carne bovina seca crua', 0, 313, 100, 19.7, 'Carnes e derivados', 'Carne bovina seca crua'),
(386, 34.5, 'Alimento da categoria Carnes e derivados, nome Coxinha de frango frita', 0, 283, 100, 9.6, 'Carnes e derivados', 'Coxinha de frango frita'),
(387, 13.9, 'Alimento da categoria Carnes e derivados, nome Croquete de carne cru', 0, 246, 100, 12, 'Carnes e derivados', 'Croquete de carne cru'),
(388, 18.1, 'Alimento da categoria Carnes e derivados, nome Croquete de carne frito', 0, 347, 100, 16.9, 'Carnes e derivados', 'Croquete de carne frito'),
(389, 47.5, 'Alimento da categoria Carnes e derivados, nome Empada de frango pré-cozida assada', 0, 358, 100, 6.9, 'Carnes e derivados', 'Empada de frango pré-cozida assada'),
(390, 35.5, 'Alimento da categoria Carnes e derivados, nome Empada de frango pré-cozida', 0, 377, 100, 7.3, 'Carnes e derivados', 'Empada de frango pré-cozida'),
(391, 0, 'Alimento da categoria Carnes e derivados, nome Frango asa com pele crua', 0, 213, 100, 18.1, 'Carnes e derivados', 'Frango asa com pele crua'),
(392, 0, 'Alimento da categoria Carnes e derivados, nome Frango caipira inteiro com pele cozido', 0, 243, 100, 23.9, 'Carnes e derivados', 'Frango caipira inteiro com pele cozido'),
(393, 0, 'Alimento da categoria Carnes e derivados, nome Frango caipira inteiro sem pele cozido', 0, 196, 100, 29.6, 'Carnes e derivados', 'Frango caipira inteiro sem pele cozido'),
(394, 0, 'Alimento da categoria Carnes e derivados, nome Frango coração cru', 0, 222, 100, 12.6, 'Carnes e derivados', 'Frango coração cru'),
(395, 0.6, 'Alimento da categoria Carnes e derivados, nome Frango coração grelhado', 0, 207, 100, 22.4, 'Carnes e derivados', 'Frango coração grelhado'),
(396, 0.1, 'Alimento da categoria Carnes e derivados, nome Frango coxa com pele assada', 0, 215, 100, 28.5, 'Carnes e derivados', 'Frango coxa com pele assada'),
(397, 0, 'Alimento da categoria Carnes e derivados, nome Frango coxa com pele crua', 0, 161, 100, 17.1, 'Carnes e derivados', 'Frango coxa com pele crua'),
(398, 0, 'Alimento da categoria Carnes e derivados, nome Frango coxa sem pele cozida', 0, 167, 100, 26.9, 'Carnes e derivados', 'Frango coxa sem pele cozida'),
(399, 0, 'Alimento da categoria Carnes e derivados, nome Frango coxa sem pele crua', 0, 120, 100, 17.8, 'Carnes e derivados', 'Frango coxa sem pele crua'),
(400, 0, 'Alimento da categoria Carnes e derivados, nome Frango fígado cru', 0, 106, 100, 17.6, 'Carnes e derivados', 'Frango fígado cru'),
(401, 7.5, 'Alimento da categoria Carnes e derivados, nome Frango filé à milanesa', 0, 221, 100, 28.5, 'Carnes e derivados', 'Frango filé à milanesa'),
(402, 0, 'Alimento da categoria Carnes e derivados, nome Frango inteiro com pele cru', 0, 226, 100, 16.4, 'Carnes e derivados', 'Frango inteiro com pele cru'),
(403, 0, 'Alimento da categoria Carnes e derivados, nome Frango inteiro sem pele assado', 0, 187, 100, 28, 'Carnes e derivados', 'Frango inteiro sem pele assado'),
(404, 0, 'Alimento da categoria Carnes e derivados, nome Frango inteiro sem pele cozido', 0, 170, 100, 25, 'Carnes e derivados', 'Frango inteiro sem pele cozido'),
(405, 0, 'Alimento da categoria Carnes e derivados, nome Frango inteiro sem pele cru', 0, 129, 100, 20.6, 'Carnes e derivados', 'Frango inteiro sem pele cru'),
(406, 0, 'Alimento da categoria Carnes e derivados, nome Frango peito com pele assado', 0, 212, 100, 33.4, 'Carnes e derivados', 'Frango peito com pele assado'),
(407, 0, 'Alimento da categoria Carnes e derivados, nome Frango peito com pele cru', 0, 149, 100, 20.8, 'Carnes e derivados', 'Frango peito com pele cru'),
(408, 0, 'Alimento da categoria Carnes e derivados, nome Frango peito sem pele cozido', 0, 163, 100, 31.5, 'Carnes e derivados', 'Frango peito sem pele cozido'),
(409, 0, 'Alimento da categoria Carnes e derivados, nome Frango peito sem pele cru', 0, 119, 100, 21.5, 'Carnes e derivados', 'Frango peito sem pele cru'),
(410, 0, 'Alimento da categoria Carnes e derivados, nome Frango peito sem pele grelhado', 0, 159, 100, 32, 'Carnes e derivados', 'Frango peito sem pele grelhado'),
(411, 0, 'Alimento da categoria Carnes e derivados, nome Frango sobrecoxa com pele assada', 0, 260, 100, 28.7, 'Carnes e derivados', 'Frango sobrecoxa com pele assada'),
(412, 0, 'Alimento da categoria Carnes e derivados, nome Frango sobrecoxa com pele crua', 0, 255, 100, 15.5, 'Carnes e derivados', 'Frango sobrecoxa com pele crua'),
(413, 0, 'Alimento da categoria Carnes e derivados, nome Frango sobrecoxa sem pele assada', 0, 233, 100, 29.2, 'Carnes e derivados', 'Frango sobrecoxa sem pele assada'),
(414, 0, 'Alimento da categoria Carnes e derivados, nome Frango sobrecoxa sem pele crua', 0, 162, 100, 17.6, 'Carnes e derivados', 'Frango sobrecoxa sem pele crua'),
(415, 4.2, 'Alimento da categoria Carnes e derivados, nome Hambúrguer bovino cru', 0, 215, 100, 13.2, 'Carnes e derivados', 'Hambúrguer bovino cru'),
(416, 6.3, 'Alimento da categoria Carnes e derivados, nome Hambúrguer bovino frito', 0, 258, 100, 20, 'Carnes e derivados', 'Hambúrguer bovino frito'),
(417, 11.3, 'Alimento da categoria Carnes e derivados, nome Hambúrguer bovino grelhado', 0, 210, 100, 13.2, 'Carnes e derivados', 'Hambúrguer bovino grelhado'),
(418, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça frango crua', 0, 218, 100, 14.2, 'Carnes e derivados', 'Lingüiça frango crua'),
(419, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça frango frita', 0, 245, 100, 18.3, 'Carnes e derivados', 'Lingüiça frango frita'),
(420, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça frango grelhada', 0, 244, 100, 18.2, 'Carnes e derivados', 'Lingüiça frango grelhada'),
(421, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça porco crua', 0, 227, 100, 16.1, 'Carnes e derivados', 'Lingüiça porco crua'),
(422, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça porco frita', 0, 280, 100, 20.5, 'Carnes e derivados', 'Lingüiça porco frita'),
(423, 0, 'Alimento da categoria Carnes e derivados, nome Lingüiça porco grelhada', 0, 296, 100, 23.2, 'Carnes e derivados', 'Lingüiça porco grelhada'),
(424, 5.8, 'Alimento da categoria Carnes e derivados, nome Mortadela', 0, 269, 100, 12, 'Carnes e derivados', 'Mortadela'),
(425, 0, 'Alimento da categoria Carnes e derivados, nome Peru congelado assado', 0, 163, 100, 26.2, 'Carnes e derivados', 'Peru congelado assado'),
(426, 0, 'Alimento da categoria Carnes e derivados, nome Peru congelado cru', 0, 94, 100, 18.1, 'Carnes e derivados', 'Peru congelado cru'),
(427, 0, 'Alimento da categoria Carnes e derivados, nome Porco bisteca crua', 0, 164, 100, 21.5, 'Carnes e derivados', 'Porco bisteca crua'),
(428, 0, 'Alimento da categoria Carnes e derivados, nome Porco bisteca frita', 0, 311, 100, 33.7, 'Carnes e derivados', 'Porco bisteca frita'),
(429, 0, 'Alimento da categoria Carnes e derivados, nome Porco bisteca grelhada', 0, 280, 100, 28.9, 'Carnes e derivados', 'Porco bisteca grelhada'),
(430, 0, 'Alimento da categoria Carnes e derivados, nome Porco costela assada', 0, 402, 100, 30.2, 'Carnes e derivados', 'Porco costela assada'),
(431, 0, 'Alimento da categoria Carnes e derivados, nome Porco costela crua', 0, 256, 100, 18, 'Carnes e derivados', 'Porco costela crua'),
(432, 0, 'Alimento da categoria Carnes e derivados, nome Porco lombo assado', 0, 210, 100, 35.7, 'Carnes e derivados', 'Porco lombo assado'),
(433, 0, 'Alimento da categoria Carnes e derivados, nome Porco lombo cru', 0, 176, 100, 22.6, 'Carnes e derivados', 'Porco lombo cru'),
(434, 0, 'Alimento da categoria Carnes e derivados, nome Porco orelha salgada crua', 0, 258, 100, 18.5, 'Carnes e derivados', 'Porco orelha salgada crua'),
(435, 0, 'Alimento da categoria Carnes e derivados, nome Porco pernil assado', 0, 262, 100, 32.1, 'Carnes e derivados', 'Porco pernil assado'),
(436, 0, 'Alimento da categoria Carnes e derivados, nome Porco pernil cru', 0, 186, 100, 20.1, 'Carnes e derivados', 'Porco pernil cru'),
(437, 0, 'Alimento da categoria Carnes e derivados, nome Porco rabo salgado cru', 0, 377, 100, 15.6, 'Carnes e derivados', 'Porco rabo salgado cru'),
(438, 1.4, 'Alimento da categoria Carnes e derivados, nome Presunto com capa de gordura', 0, 128, 100, 14.4, 'Carnes e derivados', 'Presunto com capa de gordura'),
(439, 2.1, 'Alimento da categoria Carnes e derivados, nome Presunto sem capa de gordura', 0, 94, 100, 14.3, 'Carnes e derivados', 'Presunto sem capa de gordura'),
(440, 12.9, 'Alimento da categoria Carnes e derivados, nome Quibe assado', 0, 136, 100, 14.6, 'Carnes e derivados', 'Quibe assado'),
(441, 10.8, 'Alimento da categoria Carnes e derivados, nome Quibe cru', 0, 109, 100, 12.4, 'Carnes e derivados', 'Quibe cru'),
(442, 12.3, 'Alimento da categoria Carnes e derivados, nome Quibe frito', 0, 254, 100, 14.9, 'Carnes e derivados', 'Quibe frito'),
(443, 2.9, 'Alimento da categoria Carnes e derivados, nome Salame', 0, 398, 100, 25.8, 'Carnes e derivados', 'Salame'),
(444, 0, 'Alimento da categoria Carnes e derivados, nome Toucinho cru', 0, 593, 100, 11.5, 'Carnes e derivados', 'Toucinho cru'),
(445, 0, 'Alimento da categoria Carnes e derivados, nome Toucinho frito', 0, 697, 100, 27.3, 'Carnes e derivados', 'Toucinho frito'),
(446, 7.6, 'Alimento da categoria Leite e derivados, nome Bebida láctea pêssego', 0, 55, 100, 2.1, 'Leite e derivados', 'Bebida láctea pêssego'),
(447, 4.5, 'Alimento da categoria Leite e derivados, nome Creme de Leite', 0, 221, 100, 1.5, 'Leite e derivados', 'Creme de Leite'),
(448, 1.9, 'Alimento da categoria Leite e derivados, nome Iogurte natural', 0, 51, 100, 4.1, 'Leite e derivados', 'Iogurte natural'),
(449, 5.8, 'Alimento da categoria Leite e derivados, nome Iogurte natural desnatado', 0, 41, 100, 3.8, 'Leite e derivados', 'Iogurte natural desnatado'),
(450, 9.7, 'Alimento da categoria Leite e derivados, nome Iogurte sabor abacaxi', 0, 70, 100, 2.7, 'Leite e derivados', 'Iogurte sabor abacaxi'),
(452, 9.4, 'Alimento da categoria Leite e derivados, nome Iogurte sabor pêssego', 0, 68, 100, 2.5, 'Leite e derivados', 'Iogurte sabor pêssego'),
(453, 57, 'Alimento da categoria Leite e derivados, nome Leite condensado', 0, 313, 100, 7.7, 'Leite e derivados', 'Leite condensado'),
(454, 5.2, 'Alimento da categoria Leite e derivados, nome Leite de cabra', 0, 66, 100, 3.1, 'Leite e derivados', 'Leite de cabra'),
(455, 14.2, 'Alimento da categoria Leite e derivados, nome Leite de vaca achocolatado', 0, 83, 100, 2.1, 'Leite e derivados', 'Leite de vaca achocolatado'),
(456, 53, 'Alimento da categoria Leite e derivados, nome Leite de vaca desnatado pó', 0, 362, 100, 34.7, 'Leite e derivados', 'Leite de vaca desnatado pó'),
(457, 39.2, 'Alimento da categoria Leite e derivados, nome Leite de vaca desnatado UHT', 0, 497, 100, 25.4, 'Leite e derivados', 'Leite de vaca desnatado UHT'),
(460, 15.7, 'Alimento da categoria Leite e derivados, nome Leite fermentado', 0, 70, 100, 1.9, 'Leite e derivados', 'Leite fermentado'),
(461, 3.2, 'Alimento da categoria Leite e derivados, nome Queijo minas frescal', 0, 264, 100, 17.4, 'Leite e derivados', 'Queijo minas frescal'),
(462, 3.6, 'Alimento da categoria Leite e derivados, nome Queijo minas meia cura', 0, 321, 100, 21.2, 'Leite e derivados', 'Queijo minas meia cura'),
(463, 3, 'Alimento da categoria Leite e derivados, nome Queijo mozarela', 0, 330, 100, 22.6, 'Leite e derivados', 'Queijo mozarela'),
(464, 1.7, 'Alimento da categoria Leite e derivados, nome Queijo parmesão', 0, 453, 100, 35.6, 'Leite e derivados', 'Queijo parmesão'),
(465, 5.7, 'Alimento da categoria Leite e derivados, nome Queijo pasteurizado', 0, 303, 100, 9.4, 'Leite e derivados', 'Queijo pasteurizado'),
(466, 18.5, 'Alimento da categoria Leite e derivados, nome Queijo petit suisse morango', 0, 121, 100, 5.8, 'Leite e derivados', 'Queijo petit suisse morango'),
(467, 1.9, 'Alimento da categoria Leite e derivados, nome Queijo prato', 0, 360, 100, 22.7, 'Leite e derivados', 'Queijo prato'),
(468, 2.4, 'Alimento da categoria Leite e derivados, nome Queijo requeijão cremoso', 0, 257, 100, 9.6, 'Leite e derivados', 'Queijo requeijão cremoso'),
(469, 3.8, 'Alimento da categoria Leite e derivados, nome Queijo ricota', 0, 140, 100, 12.6, 'Leite e derivados', 'Queijo ricota'),
(470, 6.4, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Bebida isotônica sabores variados', 0, 26, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Bebida isotônica sabores variados'),
(471, 1.5, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Café infusão 10%', 0, 9, 100, 0.7, 'Bebidas (alcoólicas e não alcoólicas)', 'Café infusão 10%'),
(472, 18.2, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Cana aguardente 1', 0, 216, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Cana aguardente 1'),
(474, 3.3, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Cerveja pilsen 2', 0, 41, 100, 0.6, 'Bebidas (alcoólicas e não alcoólicas)', 'Cerveja pilsen 2'),
(475, 0.4, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Chá erva-doce infusão 5%', 0, 1, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá erva-doce infusão 5%'),
(476, 0.6, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Chá mate infusão 5%', 0, 3, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá mate infusão 5%'),
(477, 0.6, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Chá preto infusão 5%', 0, 2, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá preto infusão 5%'),
(478, 5.3, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Coco água de', 0, 22, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Coco água de'),
(479, 8, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Refrigerante tipo água tônica', 0, 31, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante tipo água tônica'),
(480, 8.7, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Refrigerante tipo cola', 0, 34, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante tipo cola'),
(481, 10, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Refrigerante tipo guaraná', 0, 39, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante tipo guaraná'),
(482, 11.8, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Refrigerante tipo laranja', 0, 46, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante tipo laranja'),
(483, 10.3, 'Alimento da categoria Bebidas (alcoólicas e não alcoólicas), nome Refrigerante tipo limão', 0, 40, 100, 0, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante tipo limão'),
(484, 0.4, 'Alimento da categoria Ovos e derivados, nome Omelete de queijo', 0, 268, 100, 15.6, 'Ovos e derivados', 'Omelete de queijo'),
(485, 0.8, 'Alimento da categoria Ovos e derivados, nome Ovo de codorna inteiro cru', 0, 177, 100, 13.7, 'Ovos e derivados', 'Ovo de codorna inteiro cru'),
(486, 0, 'Alimento da categoria Ovos e derivados, nome Ovo de galinha clara cozida/10minutos', 0, 59, 100, 13.4, 'Ovos e derivados', 'Ovo de galinha clara cozida/10minutos'),
(487, 1.6, 'Alimento da categoria Ovos e derivados, nome Ovo de galinha gema cozida/10minutos', 0, 353, 100, 15.9, 'Ovos e derivados', 'Ovo de galinha gema cozida/10minutos'),
(488, 0.6, 'Alimento da categoria Ovos e derivados, nome Ovo de galinha inteiro cozido/10minutos', 0, 146, 100, 13.3, 'Ovos e derivados', 'Ovo de galinha inteiro cozido/10minutos'),
(489, 1.6, 'Alimento da categoria Ovos e derivados, nome Ovo de galinha inteiro cru', 0, 143, 100, 13, 'Ovos e derivados', 'Ovo de galinha inteiro cru'),
(490, 1.2, 'Alimento da categoria Ovos e derivados, nome Ovo de galinha inteiro frito', 0, 240, 100, 15.6, 'Ovos e derivados', 'Ovo de galinha inteiro frito'),
(491, 91.2, 'Alimento da categoria Produtos açucarados, nome Achocolatado pó', 0, 401, 100, 4.2, 'Produtos açucarados', 'Achocolatado pó'),
(492, 99.6, 'Alimento da categoria Produtos açucarados, nome Açúcar cristal', 0, 387, 100, 0.3, 'Produtos açucarados', 'Açúcar cristal'),
(493, 94.5, 'Alimento da categoria Produtos açucarados, nome Açúcar mascavo', 0, 369, 100, 0.8, 'Produtos açucarados', 'Açúcar mascavo'),
(494, 99.5, 'Alimento da categoria Produtos açucarados, nome Açúcar refinado', 0, 387, 100, 0.3, 'Produtos açucarados', 'Açúcar refinado'),
(495, 59.6, 'Alimento da categoria Produtos açucarados, nome Chocolate ao leite', 0, 540, 100, 7.2, 'Produtos açucarados', 'Chocolate ao leite'),
(496, 55.4, 'Alimento da categoria Produtos açucarados, nome Chocolate ao leite com castanha do Pará', 0, 559, 100, 7.4, 'Produtos açucarados', 'Chocolate ao leite com castanha do Pará'),
(497, 56.3, 'Alimento da categoria Produtos açucarados, nome Chocolate ao leite dietético', 0, 557, 100, 6.9, 'Produtos açucarados', 'Chocolate ao leite dietético'),
(498, 62.4, 'Alimento da categoria Produtos açucarados, nome Chocolate meio amargo', 0, 475, 100, 4.9, 'Produtos açucarados', 'Chocolate meio amargo'),
(499, 81.4, 'Alimento da categoria Produtos açucarados, nome Cocada branca', 0, 449, 100, 1.1, 'Produtos açucarados', 'Cocada branca'),
(500, 54.6, 'Alimento da categoria Produtos açucarados, nome Doce de abóbora cremoso', 0, 199, 100, 0.9, 'Produtos açucarados', 'Doce de abóbora cremoso'),
(501, 59.5, 'Alimento da categoria Produtos açucarados, nome Doce de leite cremoso', 0, 306, 100, 5.5, 'Produtos açucarados', 'Doce de leite cremoso'),
(502, 24.2, 'Alimento da categoria Produtos açucarados, nome Geléia mocotó natural', 0, 106, 100, 2.1, 'Produtos açucarados', 'Geléia mocotó natural'),
(503, 79.4, 'Alimento da categoria Produtos açucarados, nome Glicose de milho', 0, 292, 100, 0, 'Produtos açucarados', 'Glicose de milho'),
(504, 73.6, 'Alimento da categoria Produtos açucarados, nome Maria mole', 0, 301, 100, 3.8, 'Produtos açucarados', 'Maria mole'),
(505, 75.1, 'Alimento da categoria Produtos açucarados, nome Maria mole coco queimado', 0, 307, 100, 3.9, 'Produtos açucarados', 'Maria mole coco queimado'),
(506, 70.8, 'Alimento da categoria Produtos açucarados, nome Marmelada', 0, 257, 100, 0.4, 'Produtos açucarados', 'Marmelada'),
(507, 84, 'Alimento da categoria Produtos açucarados, nome Mel de abelha', 0, 309, 100, 0, 'Produtos açucarados', 'Mel de abelha'),
(508, 76.6, 'Alimento da categoria Produtos açucarados, nome Melado', 0, 297, 100, 0, 'Produtos açucarados', 'Melado'),
(509, 46.3, 'Alimento da categoria Produtos açucarados, nome Quindim', 0, 411, 100, 4.7, 'Produtos açucarados', 'Quindim'),
(510, 90.8, 'Alimento da categoria Produtos açucarados, nome Rapadura', 0, 352, 100, 1, 'Produtos açucarados', 'Rapadura'),
(511, 65.8, 'Alimento da categoria Miscelâneas, nome Café pó torrado', 0, 419, 100, 14.7, 'Miscelâneas', 'Café pó torrado'),
(512, 73.6, 'Alimento da categoria Miscelâneas, nome Capuccino pó', 0, 417, 100, 11.3, 'Miscelâneas', 'Capuccino pó'),
(513, 43.9, 'Alimento da categoria Miscelâneas, nome Fermento em pó químico', 0, 90, 100, 0.5, 'Miscelâneas', 'Fermento em pó químico'),
(514, 7.7, 'Alimento da categoria Miscelâneas, nome Fermento biológico levedura tablete', 0, 90, 100, 17, 'Miscelâneas', 'Fermento biológico levedura tablete'),
(515, 89.2, 'Alimento da categoria Miscelâneas, nome Gelatina sabores variados pó', 0, 380, 100, 8.9, 'Miscelâneas', 'Gelatina sabores variados pó'),
(516, 11.6, 'Alimento da categoria Miscelâneas, nome Sal dietético', 0, 61, 100, 3.3, 'Miscelâneas', 'Sal dietético'),
(519, 2.1, 'Alimento da categoria Miscelâneas, nome Tempero a base de sal', 0, 21, 100, 2.7, 'Miscelâneas', 'Tempero a base de sal'),
(520, 5.5, 'Alimento da categoria Outros alimentos industrializados, nome Azeitona preta conserva', 0, 194, 100, 1.2, 'Outros alimentos industrializados', 'Azeitona preta conserva'),
(521, 4.1, 'Alimento da categoria Outros alimentos industrializados, nome Azeitona verde conserva', 0, 137, 100, 0.9, 'Outros alimentos industrializados', 'Azeitona verde conserva'),
(522, 16.9, 'Alimento da categoria Outros alimentos industrializados, nome Chantilly spray com gordura vegetal', 0, 315, 100, 0.5, 'Outros alimentos industrializados', 'Chantilly spray com gordura vegetal'),
(523, 2.2, 'Alimento da categoria Outros alimentos industrializados, nome Leite de coco', 0, 166, 100, 1, 'Outros alimentos industrializados', 'Leite de coco'),
(524, 7.9, 'Alimento da categoria Outros alimentos industrializados, nome Maionese tradicional com ovos', 0, 302, 100, 0.6, 'Outros alimentos industrializados', 'Maionese tradicional com ovos'),
(525, 19.1, 'Alimento da categoria Alimentos preparados, nome Acarajé', 0, 289, 100, 8.3, 'Alimentos preparados', 'Acarajé'),
(526, 11.6, 'Alimento da categoria Alimentos preparados, nome Arroz carreteiro', 0, 154, 100, 10.8, 'Alimentos preparados', 'Arroz carreteiro'),
(527, 20.4, 'Alimento da categoria Alimentos preparados, nome Baião de dois arroz e feijão-de-corda', 0, 136, 100, 6.2, 'Alimentos preparados', 'Baião de dois arroz e feijão-de-corda'),
(528, 0.2, 'Alimento da categoria Alimentos preparados, nome Barreado', 0, 165, 100, 18.3, 'Alimentos preparados', 'Barreado'),
(529, 0, 'Alimento da categoria Alimentos preparados, nome Bife à cavalo com contra filé', 0, 291, 100, 23.7, 'Alimentos preparados', 'Bife à cavalo com contra filé'),
(530, 41.7, 'Alimento da categoria Alimentos preparados, nome Bolinho de arroz', 0, 274, 100, 8, 'Alimentos preparados', 'Bolinho de arroz'),
(531, 3.2, 'Alimento da categoria Alimentos preparados, nome Camarão à baiana', 0, 101, 100, 7.9, 'Alimentos preparados', 'Camarão à baiana'),
(532, 10.1, 'Alimento da categoria Alimentos preparados, nome Charuto de repolho', 0, 78, 100, 6.8, 'Alimentos preparados', 'Charuto de repolho'),
(533, 25.3, 'Alimento da categoria Alimentos preparados, nome Cuscuz de milho cozido com sal', 0, 113, 100, 2.2, 'Alimentos preparados', 'Cuscuz de milho cozido com sal'),
(534, 22.5, 'Alimento da categoria Alimentos preparados, nome Cuscuz paulista', 0, 142, 100, 2.6, 'Alimentos preparados', 'Cuscuz paulista'),
(535, 5.7, 'Alimento da categoria Alimentos preparados, nome Cuxá molho', 0, 80, 100, 5.6, 'Alimentos preparados', 'Cuxá molho'),
(536, 0, 'Alimento da categoria Alimentos preparados, nome Dobradinha', 0, 125, 100, 19.8, 'Alimentos preparados', 'Dobradinha'),
(537, 3, 'Alimento da categoria Alimentos preparados, nome Estrogonofe de carne', 0, 173, 100, 15, 'Alimentos preparados', 'Estrogonofe de carne'),
(538, 2.6, 'Alimento da categoria Alimentos preparados, nome Estrogonofe de frango', 0, 157, 100, 17.6, 'Alimentos preparados', 'Estrogonofe de frango'),
(539, 19.6, 'Alimento da categoria Alimentos preparados, nome Feijão tropeiro mineiro', 0, 152, 100, 10.2, 'Alimentos preparados', 'Feijão tropeiro mineiro'),
(540, 11.6, 'Alimento da categoria Alimentos preparados, nome Feijoada', 0, 117, 100, 8.7, 'Alimentos preparados', 'Feijoada'),
(541, 4.1, 'Alimento da categoria Alimentos preparados, nome Frango com açafrão', 0, 113, 100, 9.7, 'Alimentos preparados', 'Frango com açafrão'),
(542, 22.5, 'Alimento da categoria Alimentos preparados, nome Macarrão molho bolognesa', 0, 120, 100, 4.9, 'Alimentos preparados', 'Macarrão molho bolognesa'),
(543, 3.4, 'Alimento da categoria Alimentos preparados, nome Maniçoba', 0, 134, 100, 10, 'Alimentos preparados', 'Maniçoba'),
(544, 6.6, 'Alimento da categoria Alimentos preparados, nome Quibebe', 0, 86, 100, 8.6, 'Alimentos preparados', 'Quibebe'),
(545, 8.9, 'Alimento da categoria Alimentos preparados, nome Salada de legumes com maionese', 0, 96, 100, 1.1, 'Alimentos preparados', 'Salada de legumes com maionese'),
(546, 7.1, 'Alimento da categoria Alimentos preparados, nome Salada de legumes cozida no vapor', 0, 35, 100, 2, 'Alimentos preparados', 'Salada de legumes cozida no vapor'),
(547, 4.6, 'Alimento da categoria Alimentos preparados, nome Salpicão de frango', 0, 148, 100, 13.9, 'Alimentos preparados', 'Salpicão de frango'),
(548, 1.1, 'Alimento da categoria Alimentos preparados, nome Sarapatel', 0, 123, 100, 18.5, 'Alimentos preparados', 'Sarapatel'),
(549, 10.6, 'Alimento da categoria Alimentos preparados, nome Tabule', 0, 57, 100, 2, 'Alimentos preparados', 'Tabule'),
(550, 3.4, 'Alimento da categoria Alimentos preparados, nome Tacacá', 0, 47, 100, 7, 'Alimentos preparados', 'Tacacá'),
(551, 63.6, 'Alimento da categoria Alimentos preparados, nome Tapioca com manteiga', 0, 348, 100, 0.1, 'Alimentos preparados', 'Tapioca com manteiga'),
(552, 4.7, 'Alimento da categoria Alimentos preparados, nome Tucupi com pimenta-de-cheiro', 0, 27, 100, 2.1, 'Alimentos preparados', 'Tucupi com pimenta-de-cheiro'),
(553, 10.1, 'Alimento da categoria Alimentos preparados, nome Vaca atolada', 0, 145, 100, 5.1, 'Alimentos preparados', 'Vaca atolada'),
(554, 9.7, 'Alimento da categoria Alimentos preparados, nome Vatapá', 0, 255, 100, 6, 'Alimentos preparados', 'Vatapá'),
(555, 14.1, 'Alimento da categoria Alimentos preparados, nome Virado à paulista', 0, 307, 100, 10.2, 'Alimentos preparados', 'Virado à paulista'),
(556, 18.3, 'Alimento da categoria Alimentos preparados, nome Yakisoba', 0, 113, 100, 7.5, 'Alimentos preparados', 'Yakisoba'),
(557, 20.3, 'Alimento da categoria Leguminosas e derivados, nome Amendoim grão cru', 0, 544, 100, 27.2, 'Leguminosas e derivados', 'Amendoim grão cru'),
(558, 18.7, 'Alimento da categoria Leguminosas e derivados, nome Amendoim torrado salgado', 0, 606, 100, 22.5, 'Leguminosas e derivados', 'Amendoim torrado salgado'),
(559, 14.2, 'Alimento da categoria Leguminosas e derivados, nome Ervilha em vagem', 0, 88, 100, 7.5, 'Leguminosas e derivados', 'Ervilha em vagem'),
(560, 13.4, 'Alimento da categoria Leguminosas e derivados, nome Ervilha enlatada drenada', 0, 74, 100, 4.6, 'Leguminosas e derivados', 'Ervilha enlatada drenada'),
(561, 13.6, 'Alimento da categoria Leguminosas e derivados, nome Feijão carioca cozido', 0, 76, 100, 4.8, 'Leguminosas e derivados', 'Feijão carioca cozido'),
(562, 61.2, 'Alimento da categoria Leguminosas e derivados, nome Feijão carioca cru', 0, 329, 100, 20, 'Leguminosas e derivados', 'Feijão carioca cru'),
(563, 13.5, 'Alimento da categoria Leguminosas e derivados, nome Feijão fradinho cozido', 0, 78, 100, 5.1, 'Leguminosas e derivados', 'Feijão fradinho cozido'),
(564, 61.2, 'Alimento da categoria Leguminosas e derivados, nome Feijão fradinho cru', 0, 339, 100, 20.2, 'Leguminosas e derivados', 'Feijão fradinho cru'),
(565, 16.5, 'Alimento da categoria Leguminosas e derivados, nome Feijão jalo cozido', 0, 93, 100, 6.1, 'Leguminosas e derivados', 'Feijão jalo cozido'),
(566, 61.5, 'Alimento da categoria Leguminosas e derivados, nome Feijão jalo cru', 0, 328, 100, 20.1, 'Leguminosas e derivados', 'Feijão jalo cru'),
(567, 14, 'Alimento da categoria Leguminosas e derivados, nome Feijão preto cozido', 0, 77, 100, 4.5, 'Leguminosas e derivados', 'Feijão preto cozido'),
(568, 58.8, 'Alimento da categoria Leguminosas e derivados, nome Feijão preto cru', 0, 324, 100, 21.3, 'Leguminosas e derivados', 'Feijão preto cru'),
(569, 15.3, 'Alimento da categoria Leguminosas e derivados, nome Feijão rajado cozido', 0, 85, 100, 5.5, 'Leguminosas e derivados', 'Feijão rajado cozido'),
(570, 62.9, 'Alimento da categoria Leguminosas e derivados, nome Feijão rajado cru', 0, 326, 100, 17.3, 'Leguminosas e derivados', 'Feijão rajado cru'),
(571, 11.8, 'Alimento da categoria Leguminosas e derivados, nome Feijão rosinha cozido', 0, 68, 100, 4.5, 'Leguminosas e derivados', 'Feijão rosinha cozido'),
(572, 62.2, 'Alimento da categoria Leguminosas e derivados, nome Feijão rosinha cru', 0, 337, 100, 20.9, 'Leguminosas e derivados', 'Feijão rosinha cru'),
(573, 12.9, 'Alimento da categoria Leguminosas e derivados, nome Feijão roxo cozido', 0, 77, 100, 5.7, 'Leguminosas e derivados', 'Feijão roxo cozido'),
(574, 60, 'Alimento da categoria Leguminosas e derivados, nome Feijão roxo cru', 0, 331, 100, 22.2, 'Leguminosas e derivados', 'Feijão roxo cru'),
(575, 57.9, 'Alimento da categoria Leguminosas e derivados, nome Grão-de-bico cru', 0, 355, 100, 21.2, 'Leguminosas e derivados', 'Grão-de-bico cru'),
(576, 64, 'Alimento da categoria Leguminosas e derivados, nome Guandu cru', 0, 344, 100, 19, 'Leguminosas e derivados', 'Guandu cru'),
(577, 16.3, 'Alimento da categoria Leguminosas e derivados, nome Lentilha cozida', 0, 93, 100, 6.3, 'Leguminosas e derivados', 'Lentilha cozida'),
(578, 62, 'Alimento da categoria Leguminosas e derivados, nome Lentilha crua', 0, 339, 100, 23.2, 'Leguminosas e derivados', 'Lentilha crua'),
(579, 52.4, 'Alimento da categoria Leguminosas e derivados, nome Paçoca amendoim', 0, 487, 100, 16, 'Leguminosas e derivados', 'Paçoca amendoim'),
(580, 54.7, 'Alimento da categoria Leguminosas e derivados, nome Pé-de-moleque amendoim', 0, 503, 100, 13.2, 'Leguminosas e derivados', 'Pé-de-moleque amendoim'),
(581, 38.4, 'Alimento da categoria Leguminosas e derivados, nome Soja farinha', 0, 404, 100, 36, 'Leguminosas e derivados', 'Soja farinha'),
(582, 4.3, 'Alimento da categoria Leguminosas e derivados, nome Soja extrato solúvel natural fluido', 0, 39, 100, 2.4, 'Leguminosas e derivados', 'Soja extrato solúvel natural fluido'),
(583, 28.5, 'Alimento da categoria Leguminosas e derivados, nome Soja extrato solúvel pó', 0, 459, 100, 35.7, 'Leguminosas e derivados', 'Soja extrato solúvel pó'),
(584, 2.1, 'Alimento da categoria Leguminosas e derivados, nome Soja queijo (tofu)', 0, 64, 100, 6.6, 'Leguminosas e derivados', 'Soja queijo (tofu)'),
(585, 43.8, 'Alimento da categoria Leguminosas e derivados, nome Tremoço cru', 0, 381, 100, 33.6, 'Leguminosas e derivados', 'Tremoço cru'),
(586, 12.4, 'Alimento da categoria Leguminosas e derivados, nome Tremoço em conserva', 0, 121, 100, 11.1, 'Leguminosas e derivados', 'Tremoço em conserva'),
(587, 29.5, 'Alimento da categoria Nozes e sementes, nome Amêndoa torrada salgada', 0, 581, 100, 18.6, 'Nozes e sementes', 'Amêndoa torrada salgada'),
(588, 29.1, 'Alimento da categoria Nozes e sementes, nome Castanha-de-caju torrada salgada', 0, 570, 100, 18.5, 'Nozes e sementes', 'Castanha-de-caju torrada salgada'),
(589, 15.1, 'Alimento da categoria Nozes e sementes, nome Castanha-do-Brasil crua', 0, 643, 100, 14.5, 'Nozes e sementes', 'Castanha-do-Brasil crua'),
(590, 10.4, 'Alimento da categoria Nozes e sementes, nome Coco cru', 0, 406, 100, 3.7, 'Nozes e sementes', 'Coco cru'),
(591, 79.2, 'Alimento da categoria Nozes e sementes, nome Coco  verde cru', 0, 329, 100, 1.4, 'Nozes e sementes', 'Coco  verde cru'),
(593, 21.6, 'Alimento da categoria Nozes e sementes, nome Gergelim semente', 0, 584, 100, 21.2, 'Nozes e sementes', 'Gergelim semente'),
(594, 43.3, 'Alimento da categoria Nozes e sementes, nome Linhaça semente', 0, 495, 100, 14.1, 'Nozes e sementes', 'Linhaça semente'),
(595, 43.9, 'Alimento da categoria Nozes e sementes, nome Pinhão cozido', 0, 174, 100, 3, 'Nozes e sementes', 'Pinhão cozido'),
(596, 29.6, 'Alimento da categoria Nozes e sementes, nome Pupunha cozida', 0, 219, 100, 2.5, 'Nozes e sementes', 'Pupunha cozida'),
(597, 18.4, 'Alimento da categoria Nozes e sementes, nome Noz crua', 0, 620, 100, 14, 'Nozes e sementes', 'Noz crua');
ALTER TABLE PRODUTO_ALIMENTICIO ALTER COLUMN ID RESTART WITH 598;